### ISSUE TITLE
Add ConvPoint

### ISSUE THREAD

**Issue by humanpose1** [torch-points3d/torch-points3d#212]
It would be great to also add [ConvPoint](https://arxiv.org/pdf/1904.02375.pdf) in the framework.
There is an implementation [here](https://github.com/aboulch/ConvPoint) by the author in Pytorch so it's not complicated to add.

**Comment by nicolas-chaulet** [comment]
One thing to note is that the license is LGPL so we can't just copy the code across, it has to be rewritten to some extent.
