### ISSUE TITLE
Shapenet but with labels?

### ISSUE THREAD

**Issue by cinjon** [torch-points3d/torch-points3d#277]
Hi, is there a way with this repo to do ShapeNet[55] with labels? It appears like that's been distinguished as something for ModelNet but not ShapeNet. 

Thanks

**Comment by nicolas-chaulet** [comment]
Hi, 
The version of Shapenet we support is related to the Part segmentation challenge:
https://shapenet.cs.stanford.edu/iccv17/
If you'd like to contribute by adding this new dataset, we would be happy to support you! The ModelNet dataset is probably a good example to get started.

**Comment by CCInc** [comment]
Closing for now
