### ISSUE TITLE
The performance of RandLA in S3DIS？

### ISSUE THREAD

**Issue by LiDaiY** [torch-points3d/torch-points3d#292]
Has anyone tested Randla on the S3DIS? Can you achieve the result in the paper?

**Comment by nicolas-chaulet** [comment]
Hi! Randla-Net is still WIP, we haven't run it on S3DIS no. If you want to contribute, I am happy to provide some guidance about where to get started! We also have a slack channel, let us know if you'd like to join it.

**Comment by codename1995** [comment]
@nicolas-chaulet I am trying to reproduce the results of RandLA-Net on S3DIS. Could you maybe invite me to the slack channel?

**Comment by JUNJIE99** [comment]
@codename1995 Hi! Have you reproduced the results of RandLA-Net on S3DIS?

**Comment by codename1995** [comment]
> @codename1995 Hi! Have you reproduced the results of RandLA-Net on S3DIS?

No, I abandoned. But there are many attempts to do similar things in github.

**Comment by CCInc** [comment]
Closing for #236
