### ISSUE TITLE
Re-starting an interrupted run

### ISSUE THREAD

**Issue by loicland** [torch-points3d/torch-points3d#306]
Hi,

when a run crashes  (for reasons unrelated to the framework), I am not able to continue the run in the same folder, I get the following error in `torch_points3d/metrics/model_checkpoint.py`:
```
copyfile     raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/home/[...]/PTN-1-/pointnet2_largemsg.pt' and 'pointnet2_largemsg.pt' are the same file
```
It would be convenient if I could just continue the run in the same folder with the logs, models and wandb  where they were stopped. Also, the pre-processing could be avoided.

Thanks!

**Comment by nicolas-chaulet** [comment]
#405 adds support to continue a wandb run. Would that be enough?
