### ISSUE TITLE
the difference of implementing KPconv and Rsconv in Notebook-ObjectClassificationRSConv

### ISSUE THREAD

**Issue by shangguan9191** [torch-points3d/torch-points3d#401]
I got following error after i changed the model; 
![image](https://user-images.githubusercontent.com/64595972/89586878-c0a88e80-d840-11ea-99db-5ae474f4157d.png)

in order to implement KPconv for modelnet10(same for pointnet++ ?), what kind of transformation do i need?  how many changes,in forward pass ? 

or i can simply run after i create classfication folder in model and config,
!python train.py task=classification dataset=modelnet model_name=kpconv model_type=KPConvEncoder
But how can i implement init, set_input, forward and backward function. what is the difference to do classification and Segmentation task on modelnet. i know i should change torch-points3d/torch_points3d/applications/kpconv.py, but how?

**Comment by tchaton** [comment]
You have some simple examples here: https://github.com/nicolas-chaulet/torch-points3d/tree/master/examples

**Comment by shangguan91** [comment]
but one thing i am cofused about is in notebook there are a lot of step preprocessing the data, for Rsconv: SimpleBatch(pos=[12, 2048, 3], x=[12, 2048, 3], y=[12, 1]).   In simple example for Kpconv , the data:Batch(batch=[2], block_idx=10, idx_neighboors=[50, 38], pos=[2, 3], x=[2, 10], y=[50]). I just need to get model running for modelnet40 for classfication task.

**Comment by shangguan91** [comment]
i transform my data ready for trainining as following:
MultiScaleBatch(batch=[24576], multiscale=[10], pos=[24576, 3], upsample=[0], x=[24576, 3], y=[12])
it still wont work

**Comment by tchaton** [comment]
Hey @shangguan91,

I will try to add it this weekend.

Best regards,
T.C

**Comment by shangguan91** [comment]
@tchaton  
i have reimplement pointnet2. but for Kpconv, despite that i transformed data into required form, the training process still receive the wrong matrix. 
yeah, i am looking forward to your work.
Thank you!

**Comment by shangguan91** [comment]
Dear @tchaton,

Have you finished the models for classification task on the modelnet40? 

Best,
Shangguan91
