### ISSUE TITLE
Training with scannet stuck at processing

### ISSUE THREAD

**Issue by molnarszilard** [torch-points3d/torch-points3d#481]
Hi, I am trying to train a pointnet2 model with the scannet dataset.
For a while when I was running 
python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=scannet training=scannet_benchmark/pointnet2
It started processing, it wrote every file that it processed to the terminal, but after it finished, it stuck.
After the d9be23bdd2eb1cf07db9a279912fe5c3d7a426d0 update, the processing did not write everything to the terminal, but got stuck as before.
This stuck means, that nothing is written to the screen, no significant usage is detected at cpu or gpu for at least 1.5 hours.
Also the results of the processing are not saved in the data folder, so I think this means, that it does not finishes processing the files.

**Comment by nicolas-chaulet** [comment]
Hey, yes that's probably a bug. Could you try to remove the data/scannet/processed folder and launch your command again? Also make sure that you are up to date with master.
The processed folder should contain at least 3 files (train.pt, test.pt and val.pt) once processing is finished. It should print it's progress in any case so if it does not then something is broken.

**Comment by molnarszilard** [comment]
I am up to date with master, and after I deleted the folder, and re-run the command, the problem is still the same.
No progress is written while processing, and nothing appears in the progress folder.
About a week ago at least the progress were written, but yesterday I have updated my copy of the repository, and since then not even the progress is present.

**Comment by molnarszilard** [comment]
An update.
I have tried to use scannet-fixed, with that the progress of the process is shown, but after it I am getting the following:
1200/1201| scan_name: scene0706_00, data: Data(instance_bboxes=[12, 7], instance_labels=[137070], pos=[137070, 3], rgb=[137070, 3], y=[137070])
SAVING TO /media/cuda/ssd/datasets/scannet-sparse/processed/train.pt
Killed

at the scannet-sparse/processed folder I have 3 folders (raw_test, raw_train, raw_val), but only in the raw_train folder there are .pt files (scene*.pt).
The train.py files doesn't get saved, so maybe that is the problem.

**Comment by nicolas-chaulet** [comment]
what if you launch it again after that? Also, try running the process with `data.process_workers=0` for scannet-sparse. It looks like you ahve a small machine and it cannot hold the whole dataset in memory unfortunately... That's my guess as to why the KILLED happens there.

**Comment by molnarszilard** [comment]
a repeated run gives the same result, even if I reduce the num_workers to 0. If I use scannet-sparse, I have the previous state, when the progress of the process wasn't shown.
Maybe I need more ram.
Thanks anyway.

**Comment by molnarszilard** [comment]
I have checked the memory usage while process is running. Before it was killed, this process used ~56% of RAM. The total system used ~13GB/16GB of RAM (without this process 4GB is used). So it indeed requires much RAM, but it still doesn't reaches max levels.

**Comment by nicolas-chaulet** [comment]
See Issue #484. I can't reproduce on my end so really hard to debug... You could add breakpoints to figure out what lines breaks it.
