### ISSUE TITLE
Training S3DIS KILLED

### ISSUE THREAD

**Issue by molnarszilard** [torch-points3d/torch-points3d#484]
Hi, I am trying to train a pointnet2 model with the S3DIS dataset, with the following command:
python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=s3disfused training=s3dis_benchmark/pointnet2

Also the dataset is read from another location than the data folder (in conf/data/segmentation/s3disfused.yaml I have modified dataroot: my_data_path).

The training first starts to process the dataset. After about 97% it gives me a warning:
*/dataset.py:165: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  self.process()
Then it continues processing , and after it made it to 100% it writes to the terminal Killed, and it ends.

I suppose that it is killed because of the warning, do you have any idea how to solve it?

**Comment by nicolas-chaulet** [comment]
Hey, this is likely a memory issue. How many GB of RAM do you have? The message above is definitely not a problem.

**Comment by molnarszilard** [comment]
I have 16Gb of RAM and 6 GB of VRAM. Since the dataset is more than 30GB, this might be the problem.
Any solution how could I set my training to use only one AREA?

**Comment by molnarszilard** [comment]
I have checked the memory usage while process is running. Before it was killed, this process used ~57% of RAM. The total system used ~13.5GB/16GB of RAM (without this process 4GB is used). So it indeed requires much RAM, but it still doesn't reaches max levels.

**Comment by nicolas-chaulet** [comment]
Hey, it is a little tricky to reproduce (no problem on my end), the only times I have seen that was when I had too little memory. Your system memory report could be lagging a bit behind as well. Waht files are in the process folder at that point? How large are they?
