### ISSUE TITLE
Trying to determine the shape parameters of multiple objects

### ISSUE THREAD

**Issue by nikogamulin** [torch-points3d/torch-points3d#533]
Hi,

After successfully implementing the model for object shape regression that detects 8 parameters of the superellipsoid (shape parameter 1, shape parameter 2, size X, size Y, size Z, offset X, offset Y, offset Z), I am trying to create a model that would be able to determine the shape parameters of multiple objects.

The model is supposed to perform segmentation and regression: for a given output, all shapes have to be detected (segmented) and then, for every shape, 8 parameter values should be predicted. For this purpose, I have generated the dataset in which every record contains from 1 to 5 objects. Below is the dataset class I have defined:
```
class SuperQuadricsRegressionShapeMulti(Dataset):
    def __init__(self, dataset_size, points_count, dimension_max, do_normalize=True, transform=None):
        """
        Args:
            number of superquadrics to be gnerated.
        """
        super().__init__()

        used_combinations = []
        self.id2params = {}
        self.pos = []
        self.norm = []
        self.ids = []
        pbar = tqdm(total=dataset_size)
        id = 0
        records_count = 0
        while records_count < dataset_size:
            # generate 1-5 shapes and store them in the same record
            shapes_count_current = random.randrange(1, 6)
            points = []
            normals = []
            ids = []
            for i in range(shapes_count_current):
                combination_is_valid = False
                while not combination_is_valid:
                    a1, a2, a3, e1, e2, x0, y0, z0 = get_random_superquadric_parameters()
                    current_parameters_str = '{}#{}#{}#{}#{}#{}#{}#{}'.format(a1, a2, a3, e1, e2, x0, y0, z0)
                    if current_parameters_str not in used_combinations:
                        combination_is_valid = True
                used_combinations.append(current_parameters_str)
                superquadric = Superquadric(a1, a2, a3, e1, e2, x0, y0, z0, dimension_max)
                try:
                    points_current, normals_current = superquadric.get_grid(points_count)
                    if do_normalize:
                        max_offset = sq_dimensions_range[1] + sq_offset_range[1]
                        points_current = list(map(lambda x: [item / max_offset for item in x], points_current))
                    points += points_current
                    normals += normals_current
                    ids += [id] * len(points_current)

                    self.id2params[id] = np.array([a1, a2, a3, e1, e2, x0, y0, z0])
                    id += 1

                except:
                    continue
            self.pos.append(np.array(points))
            self.norm.append(np.array(normals))
            self.ids.append(ids)
            records_count += 1
            pbar.update(1)
        pbar.close()

    def __len__(self):
        return len(self.pos)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        norm = torch.from_numpy(self.norm[idx]).float()
        pos = torch.from_numpy(self.pos[idx]).float()
        y = torch.from_numpy(np.array(list((map(lambda x: self.id2params[x], self.ids[idx])))))
        return Data(norm=norm, x=norm, pos=pos, y=y)
```

Below are the sample records visualisations:
![screenshot_1](https://user-images.githubusercontent.com/17519756/103645011-a0980b00-4f57-11eb-9392-8813ab9af5d8.png)
![screenshot_4](https://user-images.githubusercontent.com/17519756/103645030-a988dc80-4f57-11eb-98a6-cbd04f4aad85.png)

The issue in the case of applying segmentation (e.g. using KPConv), I guess would be the number of classes (the number of classes is equal to the size of the dataset as each object is parametrized by unique values) and what I am trying to figure out right now is how to split the N point clouds of N objects to N sets and then predict the shape parameters of every shape (from 1 to N) similarly as in the case of single shape parameters predictions.

Maybe the above approach is not optimal and it might be better to reframe the problem. If anyone has any suggestion about how to tackle the challenge, I would really appreciate your help.

[Here is the example of single object regression I have implemented using this library](https://github.com/nikogamulin/torch-points3d/blob/master/torch_points3d/datasets/regression/superquadrics.py). So basically I want to 'upgrade' the model (or use the sequence of models) to determine the parameters of multiple shapes.

**Comment by humanpose1** [comment]
Maybe it's a bit overkill but you can get inspired by instance segmentation (where we try to predict the id and the class of each point of the point cloud) whereas semantic segmentation only tries to predict the class of each points.
You can get inspired by [pointgroup](https://arxiv.org/abs/2004.01658).
the command line to use point group on scannet 
```
poetry run python train.py task=panoptic model_name=PointGroup-PAPER model_type=pointgroup dataset=scannet-sparse training=pointgroup lr_scheduler.params.gamma=1 training.epochs=300
```

**Comment by nicolas-chaulet** [comment]
Hey! @humanpose1's idea is good, also wondering about the N classes? How would you handle that in the case of a single object in the scene?
