### ISSUE TITLE
Doubt related to iou on shapenet.

### ISSUE THREAD

**Issue by dhorka** [torch-points3d/torch-points3d#557]
Hi,
I would like to ask how the different iou reported on shapenet are calculated. The thing is I am starting to use torch-points3d and it is my first time on 3d point cloud segmentation. I run it the pointnet++ example and I obtained these results: 

```
test_loss_seg = 0.3404565453529358
    test_Cmiou = 86.95915804202365
    test_Imiou = 86.95915804202365
    test_Imiou_per_class = {'Cap': 0.8695915804202364}
```

The first thing that I would like to ask where are these metrics computed. I tried to figure it out myself, but following the code, it was not pretty clear to me where are the metrics calculated. I am trying to understand the difference between cmiou and imiou. As far as I understood reading some papers, in shapenet the Cmiou is the mean iou taking into account the "classes" and the imiou is the mean iou taking into account "the parts". Am I right? If it is correct, why I am obtaining the same value on cmiou and imiou? 

Another doubt that I would like to solve about this metric is how this mean is calculated. I mean, are you accumulating the predictions for the whole epoch?  Or doing the mean for each batch, and at the end, you do the mean of all batches?

Sorry if those are basic questions, I tried to figure out by myself, but I could not find the part of the code of all the metrics calculations done.

**Comment by nicolas-chaulet** [comment]
Hey!
Metrics for shapenet are computed here:
https://github.com/nicolas-chaulet/torch-points3d/blob/9ed21db6fa583f570cf09aff49addc200e6b1f98/torch_points3d/metrics/shapenet_part_tracker.py#L49
And yes they are a bit complicated. Cmiou is the part iou averaged per class and averaged again while instance iou is the part iou averaged across all instances. You obtain the same value because you only have one class in your case. The mean is calculated for the whole epoch.

**Comment by dhorka** [comment]
Hi, thanks for your answer. I have a couple of doubts related to the metric. 

>  Cmiou is the part iou averaged per class and averaged again while instance iou is the part iou averaged across all instances

For instance, the plane has 4 parts, first, you calculate iou for each part, then you do the average of these parts, and then you do the same for each category, and finally, you do the average through all classes. I understand that correctly?

> instance iou is the part iou averaged across all instances.

This one is just to calculate the iou for each part and then average the iou of each part of the whole split. I understand that correctly?

If I understand both metrics properly I have a doubt related to this sentence that can be found in shapenet_part_tracker:
>   It follows shapenet official formula for computing miou which treats missing part as having an iou of 1
What do you mean by a missing part?

Finally, Checking the official [website](https://shapenet.cs.stanford.edu/iccv17/) of the challenge of 3d shapenet (or at least I think that is the official website ). They say the following thing:

> Average IoU: per category average Intersection Over Union is computed for each category first by averaging across all parts on all shapes with the certain category label. Then an overall average IoU is computed through a weighted average of per category IoU. The weights are just the number of shapes in each category.

Are we doing this weighted mean on points3d?
