### ISSUE TITLE
How Can I Use Semantic3d Dataset On RandLA-Net

### ISSUE THREAD

**Issue by zcy1065670505** [torch-points3d/torch-points3d#577]
Hi 
Thank  you for your great work! Here ，I want to test Semantic3d dataset on torch-points3d existing RandLA network，But there is no semantic3d.py in folder  ./torch-points3d/datasets/segmentation/ or ./conf/data/segmentation/semantic3d.yaml.
Please tell me what should I do to make it work. Thanks!

**Comment by CCInc** [comment]
I think the randla network itself has not been implemented yet. Most of the block should be there. If you're able to try to implement it that'd be awesome!
