### ISSUE TITLE
KP Conv Google Colab

### ISSUE THREAD

**Issue by TommasoPappagallo** [torch-points3d/torch-points3d#586]
Hi Nicolas nearly there with training the KP Conv segmentation notebook just have a hick up on the penultimate line so not really an issue rather a plea for some advice ha! Adding two screen shots as you can see the data pre processing (second screen shot) works fine on a sample of my data set however I get a tensor dimension mismatch (first screen shot) at the training phase. The message is a bit cryptic as I am not sure where the dimension of 16 comes from. My dataset is composed of N by 4 where the first 3 columns are the positions and the last column is an indicator value of the object part where the object of interest has 4 parts-“ROI": [0, 1, 3, 15] defined in shapenet.py. I have been stuck for a while now so thought I would pass it by you in case you happen to have seen this error before. In any case thank you very much for being so responsive and for creating this awesome platform for all to use!
<img width="1180" alt="Screenshot 2021-04-13 at 10 43 44" src="https://user-images.githubusercontent.com/30469752/114495774-e1837800-9c48-11eb-9114-ccfe2d6cf021.png">

<img width="733" alt="Screenshot 2021-04-13 at 10 41 58" src="https://user-images.githubusercontent.com/30469752/114495747-d3355c00-9c48-11eb-9f52-9cc2953009b9.png">

**Comment by TommasoPappagallo** [comment]
Fixed this by recoding the “ROI": [0, 1, 3, 15] to “ROI": [0, 1, 2 3]. Now however I get this error: [](url)
<img width="1177" alt="Screenshot 2021-04-15 at 12 35 34" src="https://user-images.githubusercontent.com/30469752/114819221-5391c380-9de7-11eb-8fdf-6ba101b9b67f.png">

Merci :)

**Comment by TommasoPappagallo** [comment]
Hi Nicolas, thanks for getting back :) So.. my approach was to make as few
modifications needed to implement my dataset. The dataset is of features at
archeological sites in the Angkor Temple Complex in Cambodia.

Changes made are:

1. I removed the other category ids in shapenet.py and defined the 4 ROIs
(where zero is a point with no feature present) and (1,2,3) are feature
types. I still left the name "Airplane" to avoid conflicts in the code
elsewhere (preventatively). So the only changes to shapenet.py are in the
first lines as seen in the shapenet.py script attached.

2.  I then uploaded my data in this data directory DIR =
"/content/drive/MyDrive/"
under "/content/drive/MyDrive/data/shapenet/raw" I placed my data (attached
to this email in a zip file) under
"/content/drive/MyDrive/data/shapenet/raw/02691156"
and removed the other folders. I then generated the train_test_split jsons
and the synsetoffset2category.txt file.

That's it really I left everything else as is, I was hoping to avoid having
to define a whole new class for the dataset just by modifying the necessary
elements and uploading my own data. Admittedly my batch size is indeed
showing None as you point out, I wonder why that is though..

Again my great thanks for your feedback and support.

Greetings from Vientiane, Laos where I am now with the team as we go on to
do a large Lidar acquisition in the south of the country (near Champassak).

All the best,

Tommaso

**Comment by nicolas-chaulet** [comment]
Hey! It is really hard to debug like that, I Shapenet is an odd dataset in the sense that it has categories and part annotation. I am assuming you are after a semantic segmentation problem. I would recommend that you create your own dataset as opposed to trying to make Shapenet work for your use case. SemanticKitti might be a better source of inspiration:
https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/segmentation/semantickitti.py

**Comment by Ademord** [comment]
@TommasoPappagallo could you share the collab you used?
