### ISSUE TITLE
Getting error while trying to install with pip install torch-sparse  -Win10 - Build cuda_11.2.r11.2/compiler.29618528_0

### ISSUE THREAD

**Issue by paulwingert865** [torch-points3d/torch-points3d#587]
ERROR: Command errored out with exit status 1:
   command: 'C:\Users\paul.wingert\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\paul.wingert\\AppData\\Local\\Temp\\pip-install-jxzsrsui\\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\\setup.py'"'"'; __file__='"'"'C:\\Users\\paul.wingert\\AppData\\Local\\Temp\\pip-install-jxzsrsui\\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\paul.wingert\AppData\Local\Temp\pip-wheel-7l6vcnj6'
       cwd: C:\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\
  Complete output (49 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\add.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\bandwidth.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\cat.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\coalesce.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\convert.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\diag.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\eye.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\index_select.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\masked_select.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\matmul.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\metis.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\mul.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\narrow.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\padding.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\permute.py -> build\lib.win-amd64-3.8\torch_sparse
  Running setup.py clean for torch-sparse
  copying torch_sparse\reduce.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\rw.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\saint.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\sample.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\select.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\spmm.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\spspmm.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\storage.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\tensor.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\transpose.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\utils.py -> build\lib.win-amd64-3.8\torch_sparse
  copying torch_sparse\__init__.py -> build\lib.win-amd64-3.8\torch_sparse
  running build_ext
  C:\Users\paul.wingert\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
    warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
  building 'torch_sparse._convert_cpu' extension
  creating build\temp.win-amd64-3.8
  creating build\temp.win-amd64-3.8\Release
  creating build\temp.win-amd64-3.8\Release\Users
  creating build\temp.win-amd64-3.8\Release\Users\paul.wingert
  creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData
  creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local
  creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp
  creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui
  creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303
  creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\csrc
  error: could not create 'build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\csrc': Der Dateiname oder die Erweiterung ist zu lang
  
  ----------------------------------------
  ERROR: Failed building wheel for torch-sparse
Failed to build torch-sparse
Installing collected packages: torch-sparse
    Running setup.py install for torch-sparse: started
    Running setup.py install for torch-sparse: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\paul.wingert\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\paul.wingert\\AppData\\Local\\Temp\\pip-install-jxzsrsui\\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\\setup.py'"'"'; __file__='"'"'C:\\Users\\paul.wingert\\AppData\\Local\\Temp\\pip-install-jxzsrsui\\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\paul.wingert\AppData\Local\Temp\pip-record-epf7w0cc\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\paul.wingert\AppData\Local\Programs\Python\Python38\Include\torch-sparse'
         cwd: C:\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\
    Complete output (49 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\add.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\bandwidth.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\cat.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\coalesce.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\convert.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\diag.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\eye.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\index_select.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\masked_select.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\matmul.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\metis.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\mul.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\narrow.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\padding.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\permute.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\reduce.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\rw.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\saint.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\sample.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\select.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\spmm.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\spspmm.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\storage.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\tensor.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\transpose.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\utils.py -> build\lib.win-amd64-3.8\torch_sparse
    copying torch_sparse\__init__.py -> build\lib.win-amd64-3.8\torch_sparse
    running build_ext
    C:\Users\paul.wingert\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\utils\cpp_extension.py:270: UserWarning: Error checking compiler version for cl: [WinError 2] Das System kann die angegebene Datei nicht finden
      warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
    building 'torch_sparse._convert_cpu' extension
    creating build\temp.win-amd64-3.8
    creating build\temp.win-amd64-3.8\Release
    creating build\temp.win-amd64-3.8\Release\Users
    creating build\temp.win-amd64-3.8\Release\Users\paul.wingert
    creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData
    creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local
    creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp
    creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui
    creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303
    creating build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\csrc
    error: could not create 'build\temp.win-amd64-3.8\Release\Users\paul.wingert\AppData\Local\Temp\pip-install-jxzsrsui\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\csrc': Der Dateiname oder die Erweiterung ist zu lang
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\paul.wingert\AppData\Local\Programs\Python\Python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\paul.wingert\\AppData\\Local\\Temp\\pip-install-jxzsrsui\\torch-sparse_6ee92b79c6244640a11d3ae64da7b303\\setup.py'"'"';

**Comment by CCInc** [comment]
See #581
