### ISSUE TITLE
Voxelization with specific extent and dimension specific resolution

### ISSUE THREAD

**Issue by digital-idiot** [torch-points3d/torch-points3d#595]
Methods defined in `torch-points3d/torch_points3d/modules/PVCNN/utils.py` helps converting point cloud to voxels. The method `initial_voxelize` assumes that voxel resolution is same in all dimensions, i. e. voxels are approximated as volumetric cube. 
* Is it possible to make it more generic where different resolution can be  specified for each dimension?
* The voxelization is performed according to the extent of the provided point cloud. However extent derived from the point cloud may not represent the actual spatial extent due to sparsity. In that case how can these methods be adopted where min and max extent for each dimension can be specified. For example, the implementation of `points_to_voxel` function in https://github.com/traveller59/spconv/blob/master/spconv/utils/__init__.py .
---
Refer to the figure below for visual representation of the problem.

![Voxelization](https://i.imgur.com/9yzAIFh.png)

This figure shows the issue for 2D case. Here, the orange grid represents the voxels generated from the extent derived from the point cloud itself. The gray grid represents the voxels generated if custom extents are specified. My intention is to generate the voxels in gray instead of the orange voxels.

**Comment by CCInc** [comment]
Hi @digital-idiot, these functions were taken almost verbatim from https://github.com/mit-han-lab/spvnas/blob/master/core/models/utils.py for the sole purpose of the point-voxel CNN network. For generic point cloud voxelization this library uses https://github.com/rusty1s/pytorch_cluster

> Is it possible to make it more generic where different resolution can be specified for each dimension?
I believe this is possible as-is with pytorch cluster `grid_cluster`. 

> The voxelization is performed according to the extent of the provided point cloud. However extent derived from the point cloud may not represent the actual spatial extent due to sparsity. In that case how can these methods be adopted where min and max extent for each dimension can be specified. For example, the implementation of points_to_voxel function in https://github.com/traveller59/spconv/blob/master/spconv/utils/__init__.py .
If I'm understanding correctly you want to be able to set the starting and ending positions of the grid, which is also possible as-is with `grid_cluster`. 

https://github.com/rusty1s/pytorch_cluster/blob/master/torch_cluster/grid.py

**Comment by digital-idiot** [comment]
Awesome. I was indeed looking for something like https://github.com/rusty1s/pytorch_cluster. Just a quick question, The voxelized tensors from `pytorch_cluster` will be compatible here as well (specifically for `PVCNN`)?

**Comment by CCInc** [comment]
To be honest, I could never get the PVCNN working better than a regular sparseconv net. I will see if I can fix the implementation this summer. At a quick glance it honestly looks like I didn't even implement the voxelization correctly. So I don't know if it will work.

But it will definitely work for a SparseConv3D network. I suggest you use that for now until I can fix PVCNN. But either way, take a look at https://github.com/nicolas-chaulet/torch-points3d/blob/b2a69d0166a92b718eb9d143521e38760ce950d1/torch_points3d/core/data_transform/grid_transform.py#L113 to find the details on how to properly quantize using grid_cluster. You'll basically just need to reimplement that transform in your data loader with the custom parameters and add a `coords` field to the `Data` object.

**Comment by digital-idiot** [comment]
> Hi @digital-idiot, these functions were taken almost verbatim from https://github.com/mit-han-lab/spvnas/blob/master/core/models/utils.py for the sole purpose of the point-voxel CNN network.

@CCInc FYI, I tried the `voxelization` method implemented in [SPVNAS](https://github.com/mit-han-lab/spvnas) (which are the exact same functions adopted here, as you mentioned earlier) and it seems it does not work as expected (or I am doing something wrong). I opened an issue (https://github.com/mit-han-lab/spvnas/issues/55) there.

**Comment by zhijian-liu** [comment]
@CCInc, it's sorry to hear that PVCNN does not work in your case. I'm wondering if you are using PVCNN or SPVCNN when you compare that with SparseConvNet. We are eager to help you with this. Thanks!

**Comment by CCInc** [comment]
@zhijian-liu I am using the SPVCNN network as described [here](https://github.com/mit-han-lab/spvnas/blob/master/core/models/semantic_kitti/spvcnn.py). Sorry for the confusion, I will need to rename it as SPVCNN in torch-points3d. 

After my semester ends I will be checking my implementation in detail and trying to fix it. I have no doubt about your excellent code, I'm sure I missed some detail. I will let you know what I find and if I cannot figure it out! 😄

**Comment by zhijian-liu** [comment]
Sounds great!

**Comment by CCInc** [comment]
Hi @zhijian-liu , I got the SPVCNN implemented: https://github.com/CCInc/torch-points3d/pull/1/files

I've been running experiments of it on the S3DIS dataset: https://wandb.ai/allcowseatfood/s3dis-benchmark

It has about the same performance as a regular sparseconv net, I wonder if I made a mistake or if you had any tips to boost performance? In the first few epochs of training spvcnn is ahead of sparseconvnet, but the performance eventually balances out.

**Comment by zhijian-liu** [comment]
Thanks for the efforts. We haven't really evaluated the performance of SPVCNN on S3DIS before as our main benchmark is on outdoor scene segmentation. Does this repo have a benchmark for outdoor scenes (e.g., SemanticKITTI and NuScenes)?
