### ISSUE TITLE
trying semantic3d on any model 

### ISSUE THREAD

**Issue by Houssembenmid** [torch-points3d/torch-points3d#599]
hello I am working with a data similar to semantic 3d .
is there anything coming soon related to this data set to be trained with one of the network that you included.

thank you for this great work by the way

**Comment by CCInc** [comment]
Do you mean a pretrained model? We provide dataloaders for s3dis already.

**Comment by lyh840766415** [comment]
> Do you mean a pretrained model? We provide dataloaders for s3dis already.

Hello, Semantic3D, not the S3DIS
This repository may not yet support semantic3d.

**Comment by CCInc** [comment]
Sorry, I see now. That's correct, there's no dataloader for semantic3d yet. It should be pretty similar to s3dis for the dataset code. https://github.com/nicolas-chaulet/torch-points3d/blob/master/torch_points3d/datasets/segmentation/s3dis.py
