### ISSUE TITLE
KPConv and PPNet on ShapeNet-Fixed - wrongly predicted labels

### ISSUE THREAD

**Issue by thzou** [torch-points3d/torch-points3d#619]
The models KPConv and PPNet output wrongly predicted labels on the ShapeNet-Fixed dataset. These two neural networks output zeros (0s) and sometimes fours (4s) in the predicted labels tensors. However, the mIoU related metrics are correctly calculated, achieving scores of 83% and above. I am attaching the related pictures.

![ppnet](https://user-images.githubusercontent.com/18090070/121016465-7368b680-c79c-11eb-8577-1ef09395a267.png)
![kpconv](https://user-images.githubusercontent.com/18090070/121016469-74014d00-c79c-11eb-8ec2-c11e3f925061.png)

Any info on this?

**Comment by CCInc** [comment]
Could you let me know the exact steps you did so I can try and reproduce?

**Comment by thzou** [comment]
Nothing special in terms of steps. I just followed the provided instructions to run KPCONV and PPNet on shapenet-fixed dataset in the task of part-segmentation with use_category: true and no selected category in configuration files in order to run it for all categories. 

torch==1.7.0, python==3.8.5, cuda==10.2

KPCONV Configuration details: 
- task=segmentation
- model_type=kpconv
- dataset=shapenet-fixed
- model_name=KPConvPaper

PPNET Configuration details:
- task=segmentation
- model_type=ppnet
- dataset=shapenet-fixed
- model_name=PPNet
