### ISSUE TITLE
Weighted loss for KPConv

### ISSUE THREAD

**Issue by abhimandal** [torch-points3d/torch-points3d#644]
Hi,

I am using KPConv to do part-segmentation on my own dataset. My dataset currently has a very skewed distribution for classes and I want to weigh them in the loss function. I know that it can be done using `dataset.weight_classes` which is `fed to compute_loss()` https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/torch_points3d/models/segmentation/kpconv.py#L142-L146

But I want to know, how should I declare these weights? I am currently making use of `trainer.py` with some modifications and passing a single `config.yaml` as configuration for dataset, training, wandb etc. I have highly adapted my code from `shapenet examples`.

Declaring a static weight in the config or manually in the code could be an option (although I think it is wrong).
But then, I suppose these weights should be dynamic because each file can have a different distribution of classes and also within each batch. 

I hope it is clear to you. 
Thanks a lot.

**Comment by CCInc** [comment]
Hi,

If you're loading the entire dataset into memory, you can compute the weights dynamically yourself over the entire dataset, similar to how s3dis does: 
https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/torch_points3d/datasets/segmentation/s3dis.py#L212 
https://github.com/nicolas-chaulet/torch-points3d/blob/5378a2ae7ef612433acedaa497073971ec66ff09/torch_points3d/datasets/base_dataset.py#L525

If you're not loading the dataset into memory, you should precompute the weights based on the entire dataset. You shouldn't perform weight classification over batches, they should be over the entire dataset.

**Comment by abhimandal** [comment]
Thanks for the explanation. It did work for me.
I also have a very fundamental doubt regarding the `Normalization` transformation used in pre-transforms. Is it absolutely necessary to be used before using `GridSampling3D` ? I get a value error, if I remove it. Could you please explain why? 

`Traceback (most recent call last):
  File "/workspace/Storage_fast/AneurysmSegmentation/aneurysm_segmentation3d/scripts/modelling/train_chkp.py", line 125, in <module>
    trainer.fit()
  File "/workspace/Storage_fast/AneurysmSegmentation/aneurysm_segmentation3d/scripts/modelling/trainer_chkp.py", line 227, in fit
    self._train_epoch(epoch)
  File "/workspace/Storage_fast/AneurysmSegmentation/aneurysm_segmentation3d/scripts/modelling/trainer_chkp.py", line 270, in _train_epoch
    epoch, self._dataset.batch_size
  File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/models/base_model.py", line 213, in optimize_parameters
    self.forward(epoch=epoch)  # first call forward to calculate intermediate results
  File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/models/segmentation/kpconv.py", line 157, in forward
    precomputed=self.upsample,
  File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/core/base_conv/partial_dense.py", line 137, in forward
    x = self.upsample_op(data, data_skip, precomputed=pre_data)
  File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/core/spatial_ops/interpolate.py", line 46, in __call__
    raise ValueError("Precomputed indices do not match with the data given to the transform")
ValueError: Precomputed indices do not match with the data given to the transform`

**Comment by bxiang233** [comment]
> Thanks for the explanation. It did work for me. I also have a very fundamental doubt regarding the `Normalization` transformation used in pre-transforms. Is it absolutely necessary to be used before using `GridSampling3D` ? I get a value error, if I remove it. Could you please explain why?
> 
> ```
> Traceback (most recent call last):
>   File "/workspace/Storage_fast/AneurysmSegmentation/aneurysm_segmentation3d/scripts/modelling/train_chkp.py", line 125, in <module>
>     trainer.fit()
>   File "/workspace/Storage_fast/AneurysmSegmentation/aneurysm_segmentation3d/scripts/modelling/trainer_chkp.py", line 227, in fit
>     self._train_epoch(epoch)
>   File "/workspace/Storage_fast/AneurysmSegmentation/aneurysm_segmentation3d/scripts/modelling/trainer_chkp.py", line 270, in _train_epoch
>     epoch, self._dataset.batch_size
>   File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/models/base_model.py", line 213, in optimize_parameters
>     self.forward(epoch=epoch)  # first call forward to calculate intermediate results
>   File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/models/segmentation/kpconv.py", line 157, in forward
>     precomputed=self.upsample,
>   File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/core/base_conv/partial_dense.py", line 137, in forward
>     x = self.upsample_op(data, data_skip, precomputed=pre_data)
>   File "/opt/conda/envs/torchpoint/lib/python3.7/site-packages/torch_points3d/core/spatial_ops/interpolate.py", line 46, in __call__
>     raise ValueError("Precomputed indices do not match with the data given to the transform")
> ValueError: Precomputed indices do not match with the data given to the transform
> ```

Hi @abhimandal , have you already figured it out? I also met this error. Thanks!
