### ISSUE TITLE
Can I know your exact local environment?

### ISSUE THREAD

**Issue by IMSHJI** [torch-points3d/torch-points3d#647]
I've been trying Pytorch's Torch-Points-3D for a few days.
Tried Ubuntu on 16.04, 18.04, 20.04
Tried python on 3.6, 3.7, 3.8,
Tried CUDA on 10.0, 10.1, 10.2, 11.0,
Tried Pytorch on 1.7, 1.5, 1.4.

But I keep getting problems with poetry install --no-root for the same reason.
Here's why:
torch-points-kernels (0.7.0): Failed
  at ~/.poetry/lib/poetry/utils/env.py:1101 in _run
      1097│                 output = subprocess.check_output(
      1098│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1099│                 )
      1100│         except CalledProcessError as e:
    → 1101│             raise EnvCommandError(e, input=input_)
      1102│ 
      1103│         return decode(output)
      1104│ 
      1105│     def execute(self, bin, *args, **kwargs):

Can I know the local specs you did and the exact environment?

I tried TP3D referring to the following two sites,
_https://torch-points3d.readthedocs.io/en/latest/src/gettingstarted.html_
Developer guidelines at _https://github.com/nicolas-chaulet/torch-points3d_
but, It seems the two sites have different prerequisites. Also, if you look at the cases where various problems occur, there are also cases where Pytorch 1.4 performed well, unlike the prerequisites (Pytorch 1.7 or higher, etc.)

p.s. graphic card is RTX3070.

**Comment by nicolas-chaulet** [comment]
It could be the graphic card, looks like torch-points-kernel could not compile properly. Added pre commit ci

**Comment by IMSHJI** [comment]
I have confirmed that there is a problem with the NVIDIA graphics driver.
It was said that the RTX series basically supports CUDA11.1 or later. (https://en.wikipedia.org/wiki/CUDA#Version_features_and_specifications)
I changed CUDA and tried TP3D in Python 3.7 version and Pytorch 1.9 version.
During pip install torch-points3d, no error occurred the first time, but I see an error in the middle in python -m unittest -v . Also, after the test is finished, three errors occur, but these are errors about the test_basedataset and test_sparsconv files. (torchsparse now found error)
**In conclusion, if you follow the installation process in Getting started, TP3D will generate an error.
**Following Poetry will result in an error.
**Only when I did pip install torch-points3d , I got a very small error.

Additionally, I tried python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg data=segmentation/shapenet-fixed in the text and it worked! (except for potry run)
A file such as pointnet2_charlesssg.pt has been created in the outputs folder, is there no way to visualize it?
I open viz_shapenet.ipynb in forward_scripts with jupyter notebook but I get an error.

**Comment by IMSHJI** [comment]
Do you happen to know the local environment where the error is not occurring at all?
I'm trying with a different graphic card. (GTX 970)

I'd like to know the exact CUDA, Python, Pytorch version without the error.
I am going to try it on CUDA 10.0, Pytorch 1.7, Python 3.7.

**Comment by CCInc** [comment]
@IMSHJI you'll have to install torchsparse if you want all the tests to pass, as the message indicates

**Comment by IMSHJI** [comment]
> @IMSHJI 메시지가 나타내는 대로 모든 테스트를 통과하려면 torchsparse를 설치해야 합니다.

I installed torch-sparse. (Ver. 0.6.9)
However, the related issue was torchsparse error without '-', which is still there after the fix to add '-' to test.x.py file.

**Comment by IMSHJI** [comment]
> @IMSHJI you'll have to install torchsparse if you want all the tests to pass, as the message indicates

I installed torch-sparse. (Ver. 0.6.9)
However, the related issue was torchsparse error without '-', which is still there after the fix to add '-' to test.x.py file.

**Comment by IMSHJI** [comment]
After I tried TP3D and succeeded in the example script, I have an earnest wish to apply it to the 3D point cloud data I have...

**Comment by bxiang233** [comment]
Hi @IMSHJI , have you already solved this problem? I also tried CUDA 11.1, Python 3.7 version and Pytorch 1.9 version. However, when I run "python -m unittest -v", I still got errors.
