### ISSUE TITLE
How to run randlanet model with on s3dis dataset

### ISSUE THREAD

**Issue by ginobilinie** [torch-points3d/torch-points3d#650]
Hi, I have tried to run the randlanet on s3dis dataset, however, I encountered a series of bugs, for example, such as num_features, index out of range and so on. I have fixed part of them, but it is still not working. Here is my running command:

python train.py task=segmentation models=segmentation/randlanet model_name=Randlanet_Conv data=segmentation/s3disfused-fixed

Can you please tell me what's the config should I run for the randlanet on S3DIS?

Thanks.

**Comment by ginobilinie** [comment]
Even if I switch the model to kpconv, the running is killed on s3dis. I think it is due to the s3dis dataloader. I have debugged the s3dis.py, and I found self.slices is not assigned. The __get_item__ for s3dis is from get_random, but it will cause error after wrapped in dataloader.

command:
python train.py task=segmentation models=segmentation/kpconv model_name=KPConvPaper data=segmentation/s3disfused training=s3dis_benchmark/kpconv

environment:
ubuntu 18.04
cuda 10.2
pytorch 1.8

error:

  File "torch_points3d/trainer.py", line 201, in _train_epoch
    for ind, data in enumerate(train_loader):


Error executing job with overrides: ['task=segmentation', 'models=segmentation/kpconv', 'model_name=KPConvPaper', 'data=segmentation/s3disfused', 'training=s3dis_benchmark/kpconv']

**Comment by parkitny** [comment]
Have you been able to solve this issue @ginobilinie ?
