### ISSUE TITLE
Is it possible to use points3d for keypoint detection?

### ISSUE THREAD

**Issue by zhang-qiang-github** [torch-points3d/torch-points3d#661]
Currently, I want to detect some keypoint in point cloud. Is it possible to implement is using torch-points3d? Could you please give me a demo?

**Comment by humanpose1** [comment]
Hi @zhang-qiang-github, a keypoint detector has not been implemented yet, but It is possible to implement it using torch-points3d frameworks and datasets :). 
Point cloud descriptors (such as FCGF) are available, and you can change the convolution (KPConv or Pointnet++).
