### ISSUE TITLE
Can't get attribute 'UntypedNode' on omegaconf.nodes

### ISSUE THREAD

**Issue by davodogster** [torch-points3d/torch-points3d#669]
Hi, Thanks for the awesome repo. Looking forward to training it on my own datasets.

The error occurs when I run:
![image](https://user-images.githubusercontent.com/46079516/133547344-4ea719f5-6d45-4587-91f0-ad146e32f987.png)

![image](https://user-images.githubusercontent.com/46079516/133535272-47a32f71-9a4f-4628-9144-650422a5ee70.png)

I have installed torch-points3d with poetry on ubuntu 20.04, CUDA 11.4, Torch11.1. (Inside an existing points3d conda env)

Omega Version:
![image](https://user-images.githubusercontent.com/46079516/133535400-348cb74d-c8da-4e07-a616-5197b4b21ca4.png)

Hydra:
![image](https://user-images.githubusercontent.com/46079516/133535471-68d7ae3f-7808-4d74-9e96-a20651e554ee.png)

Tests (most passed):

![image](https://user-images.githubusercontent.com/46079516/133535354-b8ee1281-54ac-40c5-a488-ddf411e724aa.png)

Do you know how I can fix the error? Cheers, Sam

**Comment by humanpose1** [comment]
Yes, the version of hydra have been updated. So it raises an error when you load a weight. You can use this [script.](https://github.com/nicolas-chaulet/torch-points3d/blob/master/scripts/omegaconf2dict.py) But when executing the script you need the previous version of OmegaConf.

**Comment by davodogster** [comment]
Hi @humanpose1 Thanks for that script. Do you know when and where I run the script so I can get around the error above?

**Comment by humanpose1** [comment]
Sorry for my late response, I was busy. 

When you call the method `from_pretrained`, it stores a pretrained models  in `torch_points3d/applications/weights`.
When the pt file are downloaded, you need to apply the script on these pt files (using the old version of Omegaconf v 1.4.1 or older).
