### ISSUE TITLE
Need help with 3 issues --- PartSegmentationKPConv.ipynb on Google Colab

### ISSUE THREAD

**Issue by ricemcm** [torch-points3d/torch-points3d#674]
Hi Nicolas,

I love the idea behind your paper, which I linked to from here: [Your medium.com article on torch_points3D.](https://towardsdatascience.com/torch-points3d-a-unifying-framework-for-deep-learning-on-point-clouds-94115c0be4fb)

I was looking to see how torch_points3d might be used in Google Colab, and I found this: [Your PartSegmentationKPConv.ipynb notebook.](https://colab.research.google.com/github/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb)

When I ran your notebook, I encountered 3 issues (shown below), and I’m hoping I can get your insights as to what I can do. To replicate my steps, all you have to do is run the notebook with a GPU runtime. (For ISSUE #3, note that I set `USE_NORMALS` to `False`.)

Do you see these issues when you execute?

Thanks for any help!
Justin

---

# **ISSUE #1—Older version of jupyter-client**

When executing the first block…

```python
# Setup packages can take some time (30 minutes or so)
!pip install pyvista pytorch-lightning
!pip install --upgrade jsonschema
!pip install torch-points3d
!apt-get install -qq xvfb libgl1-mesa-glx
```

I experience this error…

```python
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbclient 0.5.4 requires jupyter-client>=6.1.5, but you have jupyter-client 5.3.5 which is incompatible.
```

I could update `jupyter-client` to be the latest version, but I am not certain if Google Colab has that version for a reason.

(For me, the overall install process takes 1 hour and 2 minutes.)

---

# **ISSUE #2—Some problem with “PYVISTA_PLOT_THEME”**

The block below executes just fine…

```python
# Needed for remote rendering 
import os
os.environ["DISPLAY"] = ":1.0"
os.environ["PYVISTA_OFF_SCREEN"]="true"
os.environ["PYVISTA_PLOT_THEME"]="true"
os.environ["PYVISTA_USE_PANEL"]="true"
os.environ["PYVISTA_AUTO_CLOSE"]="false"
os.system("Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &")
```

But then when executing the following block…

```python
import os
import sys
from omegaconf import OmegaConf
import pyvista as pv
import torch
import numpy as np
```

I experience this error…

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-3-b22d8ea74fb2> in <module>()
      2 import sys
      3 from omegaconf import OmegaConf
----> 4 import pyvista as pv
      5 import torch
      6 import numpy as np

/usr/local/lib/python3.7/dist-packages/pyvista/__init__.py in <module>()
     29 # Set preferred plot theme
     30 if 'PYVISTA_PLOT_THEME' in os.environ:
---> 31     set_plot_theme(os.environ['PYVISTA_PLOT_THEME'].lower())
     32 
     33 # get the int type from vtk

/usr/local/lib/python3.7/dist-packages/pyvista/themes.py in set_plot_theme(theme)
    123             warnings.warn('use "dark" instead of "night" theme', PyvistaDeprecationWarning)
    124             theme = 'dark'
--> 125         new_theme_type = _ALLOWED_THEMES[theme].value
    126         pyvista.global_theme.load_theme(new_theme_type())
    127     elif isinstance(theme, DefaultTheme):

/usr/lib/python3.7/enum.py in __getitem__(cls, name)
    355 
    356     def __getitem__(cls, name):
--> 357         return cls._member_map_[name]
    358 
    359     def __iter__(cls):

KeyError: 'true'
```

I can get the error to go away by undoing the setting of the `PYVISTA_PLOT_THEME` env var…

```python
del os.environ["PYVISTA_PLOT_THEME"]
```

Then rerunning the import block…

```python
import os
import sys
from omegaconf import OmegaConf
import pyvista as pv
import torch
import numpy as np
```

---

# **ISSUE #3 — Loading the data (plus link to what I tried to fix it)**

When trying to load the data…

```python
# The first time you run this cell, it will download the dataset 
from torch_points3d.datasets.segmentation import ShapeNetDataset
dataset = ShapeNetDataset(params)
dataset
```

I get the following error about `PyTorch` and `torch_sparse` being compiled with different `CUDA` versions…

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-ce6f4dc3fe5d> in <module>()
      1 # The first time you run this cell, it will download the dataset
----> 2 from torch_points3d.datasets.segmentation import ShapeNetDataset
      3 dataset = ShapeNetDataset(params)
      4 dataset

/usr/local/lib/python3.7/dist-packages/torch_points3d/datasets/segmentation/__init__.py in <module>()
      1 IGNORE_LABEL: int = -1
      2 
----> 3 from .shapenet import ShapeNet, ShapeNetDataset
      4 from .s3dis import S3DISFusedDataset, S3DIS1x1Dataset, S3DISOriginalFused, S3DISSphere
      5 from .scannet import ScannetDataset, Scannet

/usr/local/lib/python3.7/dist-packages/torch_points3d/datasets/segmentation/shapenet.py in <module>()
      8 import torch
      9 
---> 10 from torch_geometric.data import Data, InMemoryDataset, extract_zip
     11 from torch_geometric.io import read_txt_array
     12 import torch_geometric.transforms as T

/usr/local/lib/python3.7/dist-packages/torch_geometric/__init__.py in <module>()
      3 
      4 from .debug import is_debug_enabled, debug, set_debug
----> 5 import torch_geometric.data
      6 import torch_geometric.transforms
      7 import torch_geometric.utils

/usr/local/lib/python3.7/dist-packages/torch_geometric/data/__init__.py in <module>()
----> 1 from .data import Data
      2 from .temporal import TemporalData
      3 from .batch import Batch
      4 from .dataset import Dataset
      5 from .in_memory_dataset import InMemoryDataset

/usr/local/lib/python3.7/dist-packages/torch_geometric/data/data.py in <module>()
      6 import torch
      7 import torch_geometric
----> 8 from torch_sparse import coalesce, SparseTensor
      9 from torch_geometric.utils import (contains_isolated_nodes,
     10                                    contains_self_loops, is_undirected)

/usr/local/lib/python3.7/dist-packages/torch_sparse/__init__.py in <module>()
     29     if t_major != major:
     30         raise RuntimeError(
---> 31             f'Detected that PyTorch and torch_sparse were compiled with '
     32             f'different CUDA versions. PyTorch has CUDA version '
     33             f'{t_major}.{t_minor} and torch_sparse has CUDA version '

RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 11.1. Please reinstall the torch_sparse that matches your PyTorch install.
```

To attempt a fix, I tried the solutions given here…

[https://stackoverflow.com/questions/60236134/pytorch-geometric-cuda-installation-issues-on-google-colab](https://stackoverflow.com/questions/60236134/pytorch-geometric-cuda-installation-issues-on-google-colab)

But nothing worked (or user error), so I’m at an impasse.

**Comment by ricemcm** [comment]
On **ISSUE #1**, I could update jupyter-client to be the latest version, but I am not certain if Google Colab has that version for a reason.

On **ISSUE #3**, I should mention that I set `USE_NORMALS` to `False`.

**Comment by Stakhan** [comment]
Hi @ricemcm,

About your issue #3, pre-compiled binaires of torch-sparse for many OS/CUDA/PyTorch combinations can be installed via pip and Anaconda from a specific repository as explained on their github: https://github.com/rusty1s/pytorch_sparse . In your case, for pytorch 1.8 ans CUDA 10.2, you could use the following command:
```
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.8.0+cu102.html

```

**Comment by ricemcm** [comment]
Thanks for the reply, @Stakhan :)

I tried your solution, and it still results in the same error --- this is because torch_sparse has the newer CUDA build and is already satisfied by the initial install:

>"PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 11.1. Please reinstall the torch_sparse that matches your PyTorch install."

So, running...

```python
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.8.0+cu102.html
```
...tells me:

```
Looking in links: https://data.pyg.org/whl/torch-1.8.0+cu102.html
Requirement already satisfied: torch-sparse in /usr/local/lib/python3.7/dist-packages (0.6.12)
Requirement already satisfied: scipy in /usr/local/lib/python3.7/dist-packages (from torch-sparse) (1.4.1)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.7/dist-packages (from scipy->torch-sparse) (1.19.5)
```

I tried updating pytorch...

```python
!pip install --upgrade pytorch
```

...but I got the following error:

```
Collecting pytorch
  Downloading pytorch-1.0.2.tar.gz (689 bytes)
Building wheels for collected packages: pytorch
  Building wheel for pytorch (setup.py) ... error
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
Installing collected packages: pytorch
    Running setup.py install for pytorch ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eg0ow19l/pytorch_165118ec779c41df945ddfb3e037652d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eg0ow19l/pytorch_165118ec779c41df945ddfb3e037652d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_i82hmtf/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/pytorch Check the logs for full command output.
```

Any ideas?
Thanks!

**Comment by Stakhan** [comment]
Hi @ricemcm,

You just need to be a bit manual here:
```
pip uninstall torch-sparse
```
Then :
```
pip install torch-sparse -f https://data.pyg.org/whl/torch-1.8.0+cu102.html
```
By the way, make sure that the pytorch version that you have already installed matches with the repository's url and don't hesitate to modify it accordingly ;)

**Comment by SibiAkkash** [comment]
> Hi Nicolas,
> 
> I love the idea behind your paper, which I linked to from here: [Your medium.com article on torch_points3D.](https://towardsdatascience.com/torch-points3d-a-unifying-framework-for-deep-learning-on-point-clouds-94115c0be4fb)
> 
> I was looking to see how torch_points3d might be used in Google Colab, and I found this: [Your PartSegmentationKPConv.ipynb notebook.](https://colab.research.google.com/github/nicolas-chaulet/torch-points3d/blob/master/notebooks/PartSegmentationKPConv.ipynb)
> 
> When I ran your notebook, I encountered 3 issues (shown below), and I’m hoping I can get your insights as to what I can do. To replicate my steps, all you have to do is run the notebook with a GPU runtime. (For ISSUE #3, note that I set `USE_NORMALS` to `False`.)
> 
> Do you see these issues when you execute?
> 
> Thanks for any help! Justin
> 
> # **ISSUE #1—Older version of jupyter-client**
> When executing the first block…
> 
> ```python
> # Setup packages can take some time (30 minutes or so)
> !pip install pyvista pytorch-lightning
> !pip install --upgrade jsonschema
> !pip install torch-points3d
> !apt-get install -qq xvfb libgl1-mesa-glx
> ```
> 
> I experience this error…
> 
> ```python
> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> nbclient 0.5.4 requires jupyter-client>=6.1.5, but you have jupyter-client 5.3.5 which is incompatible.
> ```
> 
> I could update `jupyter-client` to be the latest version, but I am not certain if Google Colab has that version for a reason.
> 
> (For me, the overall install process takes 1 hour and 2 minutes.)
> 
> # **ISSUE #2—Some problem with “PYVISTA_PLOT_THEME”**
> The block below executes just fine…
> 
> ```python
> # Needed for remote rendering 
> import os
> os.environ["DISPLAY"] = ":1.0"
> os.environ["PYVISTA_OFF_SCREEN"]="true"
> os.environ["PYVISTA_PLOT_THEME"]="true"
> os.environ["PYVISTA_USE_PANEL"]="true"
> os.environ["PYVISTA_AUTO_CLOSE"]="false"
> os.system("Xvfb :1 -screen 0 1024x768x24 > /dev/null 2>&1 &")
> ```
> 
> But then when executing the following block…
> 
> ```python
> import os
> import sys
> from omegaconf import OmegaConf
> import pyvista as pv
> import torch
> import numpy as np
> ```
> 
> I experience this error…
> 
> ```python
> ---------------------------------------------------------------------------
> KeyError                                  Traceback (most recent call last)
> <ipython-input-3-b22d8ea74fb2> in <module>()
>       2 import sys
>       3 from omegaconf import OmegaConf
> ----> 4 import pyvista as pv
>       5 import torch
>       6 import numpy as np
> 
> /usr/local/lib/python3.7/dist-packages/pyvista/__init__.py in <module>()
>      29 # Set preferred plot theme
>      30 if 'PYVISTA_PLOT_THEME' in os.environ:
> ---> 31     set_plot_theme(os.environ['PYVISTA_PLOT_THEME'].lower())
>      32 
>      33 # get the int type from vtk
> 
> /usr/local/lib/python3.7/dist-packages/pyvista/themes.py in set_plot_theme(theme)
>     123             warnings.warn('use "dark" instead of "night" theme', PyvistaDeprecationWarning)
>     124             theme = 'dark'
> --> 125         new_theme_type = _ALLOWED_THEMES[theme].value
>     126         pyvista.global_theme.load_theme(new_theme_type())
>     127     elif isinstance(theme, DefaultTheme):
> 
> /usr/lib/python3.7/enum.py in __getitem__(cls, name)
>     355 
>     356     def __getitem__(cls, name):
> --> 357         return cls._member_map_[name]
>     358 
>     359     def __iter__(cls):
> 
> KeyError: 'true'
> ```
> 
> I can get the error to go away by undoing the setting of the `PYVISTA_PLOT_THEME` env var…
> 
> ```python
> del os.environ["PYVISTA_PLOT_THEME"]
> ```
> 
> Then rerunning the import block…
> 
> ```python
> import os
> import sys
> from omegaconf import OmegaConf
> import pyvista as pv
> import torch
> import numpy as np
> ```
> 
> # **ISSUE #3 — Loading the data (plus link to what I tried to fix it)**
> When trying to load the data…
> 
> ```python
> # The first time you run this cell, it will download the dataset 
> from torch_points3d.datasets.segmentation import ShapeNetDataset
> dataset = ShapeNetDataset(params)
> dataset
> ```
> 
> I get the following error about `PyTorch` and `torch_sparse` being compiled with different `CUDA` versions…
> 
> ```python
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-10-ce6f4dc3fe5d> in <module>()
>       1 # The first time you run this cell, it will download the dataset
> ----> 2 from torch_points3d.datasets.segmentation import ShapeNetDataset
>       3 dataset = ShapeNetDataset(params)
>       4 dataset
> 
> /usr/local/lib/python3.7/dist-packages/torch_points3d/datasets/segmentation/__init__.py in <module>()
>       1 IGNORE_LABEL: int = -1
>       2 
> ----> 3 from .shapenet import ShapeNet, ShapeNetDataset
>       4 from .s3dis import S3DISFusedDataset, S3DIS1x1Dataset, S3DISOriginalFused, S3DISSphere
>       5 from .scannet import ScannetDataset, Scannet
> 
> /usr/local/lib/python3.7/dist-packages/torch_points3d/datasets/segmentation/shapenet.py in <module>()
>       8 import torch
>       9 
> ---> 10 from torch_geometric.data import Data, InMemoryDataset, extract_zip
>      11 from torch_geometric.io import read_txt_array
>      12 import torch_geometric.transforms as T
> 
> /usr/local/lib/python3.7/dist-packages/torch_geometric/__init__.py in <module>()
>       3 
>       4 from .debug import is_debug_enabled, debug, set_debug
> ----> 5 import torch_geometric.data
>       6 import torch_geometric.transforms
>       7 import torch_geometric.utils
> 
> /usr/local/lib/python3.7/dist-packages/torch_geometric/data/__init__.py in <module>()
> ----> 1 from .data import Data
>       2 from .temporal import TemporalData
>       3 from .batch import Batch
>       4 from .dataset import Dataset
>       5 from .in_memory_dataset import InMemoryDataset
> 
> /usr/local/lib/python3.7/dist-packages/torch_geometric/data/data.py in <module>()
>       6 import torch
>       7 import torch_geometric
> ----> 8 from torch_sparse import coalesce, SparseTensor
>       9 from torch_geometric.utils import (contains_isolated_nodes,
>      10                                    contains_self_loops, is_undirected)
> 
> /usr/local/lib/python3.7/dist-packages/torch_sparse/__init__.py in <module>()
>      29     if t_major != major:
>      30         raise RuntimeError(
> ---> 31             f'Detected that PyTorch and torch_sparse were compiled with '
>      32             f'different CUDA versions. PyTorch has CUDA version '
>      33             f'{t_major}.{t_minor} and torch_sparse has CUDA version '
> 
> RuntimeError: Detected that PyTorch and torch_sparse were compiled with different CUDA versions. PyTorch has CUDA version 10.2 and torch_sparse has CUDA version 11.1. Please reinstall the torch_sparse that matches your PyTorch install.
> ```
> 
> To attempt a fix, I tried the solutions given here…
> 
> https://stackoverflow.com/questions/60236134/pytorch-geometric-cuda-installation-issues-on-google-colab
> 
> But nothing worked (or user error), so I’m at an impasse.

For the pyvista error, do `os.environ["PYVISTA_PLOT_THEME"]="dark"`

**Comment by SibiAkkash** [comment]
@ricemcm for the pyvista error, do `os.environ["PYVISTA_PLOT_THEME"]="dark"`.
PYVISTA_PLOT_THEME can either be `dark` or `light`,  `true` is an invalid key.

**Comment by CCInc** [comment]
Closing for now, let me know if still an issue!
