### ISSUE TITLE
Unable to install on clean new virtual environment

### ISSUE THREAD

**Issue by Ilyas-Malik** [torch-points3d/torch-points3d#703]
Hello guys,
I hope you're doing great.

I'm posting this because I'm unable to install torchpoint3d, here are my specs:
- Windows 10 pro
- Graphics card: NVIDIA GeForce RTX 3070 Ti, CUDA 11.4.94
- Created new python virtual environment with anaconda python 3.9.7
- Used conda install pytorch==1.9.0 torchvision==0.10.0 torchaudio==0.9.0 cudatoolkit=11.3 -c pytorch -c conda-forge  to get pytorch
- Used "pip install torch-points3d" which raised many "ERROR: Failed building wheel for (package)" for some and finally this error: "(stuff) FileNotFoundError: [WinError 2] The system cannot find the file specified error: command 'C:\\Users\\Pc\\anaconda3\\envs\\point3d\\python.exe' failed with exit code 1 
----------------------------------------- ERROR: Command errored out with exit status 1:  (stuff)"

Sorry for the long message but I'm hoping someone has a quick fix for that.
Thank you in advance !

**Comment by CCInc** [comment]
Please post the whole error message on a gist or such, and try to see if you can identify the issue. It's likely a compilation or environment error
