### ISSUE TITLE
about transform

### ISSUE THREAD

**Issue by zbl-96** [torch-points3d/torch-points3d#704]
#https://github.com/nicolas-chaulet/torch-points3d/commit/9a3b8fe9ada7037a60df94ad2f357b33af590885#r62259455
I found that this code may not be working as expected.GridSampling3D func dont change the pos.
Did I misunderstand?

**Comment by CCInc** [comment]
I'm not sure I understand. You linked to SphereCrop but you seem to be talking about GridSampling3D.

**Comment by zbl-96** [comment]
sorry mymistake
