### ISSUE TITLE
ERROR: Failed building wheel for torch-points-kernels

### ISSUE THREAD

**Issue by Sandeepjalui93** [torch-points3d/torch-points3d#720]
My system specification : 

PyTorch :- 1.11.0, 
Python :- 3.8.8, 
Cudatoolkit :- 11.3.1, 
CUDA :- 11.2, 
cudnn :- 8.2.1

I am trying to install torch-points3d, but unfortunately, I am getting this error "ERROR: Failed building wheel for torch-points-kernels"
Below is the output from anaconda terminal

Collecting torch-points3d
  Using cached torch_points3d-1.3.0-py3-none-any.whl (349 kB)
Collecting pytorch_metric_learning<0.10.0,>=0.9.87.dev0
  Using cached pytorch_metric_learning-0.9.99-py3-none-any.whl (105 kB)
Collecting gdown<4.0.0,>=3.12.0
  Using cached gdown-3.15.0-py3-none-any.whl
Requirement already satisfied: torch-sparse<0.7.0,>=0.6.0 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (0.6.13)
Collecting open3d==0.10.0.0
  Using cached open3d-0.10.0.0-cp38-cp38-win_amd64.whl (2.5 MB)
Collecting scikit-image<0.17.0,>=0.16.2
  Using cached scikit_image-0.16.2-cp38-cp38-win_amd64.whl (25.8 MB)
Requirement already satisfied: tqdm<5.0,>=4.40 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (4.59.0)
Requirement already satisfied: torch-scatter<3.0.0,>=2.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (2.0.9)
Collecting wandb<0.9.0,>=0.8.18
  Using cached wandb-0.8.36-py2.py3-none-any.whl (1.4 MB)
Collecting torch-points-kernels<0.7.0,>=0.6.6
  Using cached torch-points-kernels-0.6.10.tar.gz (45 kB)
  Preparing metadata (setup.py) ... done
Collecting hydra-core<0.12.0,>=0.11.2
  Using cached hydra_core-0.11.3-py3-none-any.whl (72 kB)
Requirement already satisfied: numpy<1.20.0 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (1.19.5)
Requirement already satisfied: torch-cluster<2.0.0,>=1.5.6 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (1.6.0)
Requirement already satisfied: tensorboard<3.0,>=2.1 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (2.7.0)
Collecting numba<0.51.0,>=0.50.0
  Using cached numba-0.50.1-cp38-cp38-win_amd64.whl (2.2 MB)
Collecting plyfile<0.8.0,>=0.7.2
  Using cached plyfile-0.7.4-py3-none-any.whl (39 kB)
Collecting torchnet<0.0.5,>=0.0.4
  Using cached torchnet-0.0.4-py3-none-any.whl
Requirement already satisfied: matplotlib<4.0,>=3.1 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (3.3.4)
Requirement already satisfied: torch<2.0.0,>=1.7.0 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-points3d) (1.11.0)
Collecting torch-geometric<2.0.0,>=1.3.2
  Using cached torch_geometric-1.7.2-py3-none-any.whl
Requirement already satisfied: ipywidgets in c:\users\sjalu\anaconda3\lib\site-packages (from open3d==0.10.0.0->torch-points3d) (7.6.3)
Requirement already satisfied: widgetsnbextension in c:\users\sjalu\anaconda3\lib\site-packages (from open3d==0.10.0.0->torch-points3d) (3.5.1)
Requirement already satisfied: notebook in c:\users\sjalu\anaconda3\lib\site-packages (from open3d==0.10.0.0->torch-points3d) (6.3.0)
Requirement already satisfied: requests[socks]>=2.12.0 in c:\users\sjalu\anaconda3\lib\site-packages (from gdown<4.0.0,>=3.12.0->torch-points3d) (2.25.1)
Requirement already satisfied: filelock in c:\users\sjalu\anaconda3\lib\site-packages (from gdown<4.0.0,>=3.12.0->torch-points3d) (3.6.0)
Requirement already satisfied: six in c:\users\sjalu\anaconda3\lib\site-packages (from gdown<4.0.0,>=3.12.0->torch-points3d) (1.15.0)
Collecting omegaconf<1.5,>=1.4
  Using cached omegaconf-1.4.1-py3-none-any.whl (14 kB)
Requirement already satisfied: pillow>=6.2.0 in c:\users\sjalu\anaconda3\lib\site-packages (from matplotlib<4.0,>=3.1->torch-points3d) (8.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in c:\users\sjalu\anaconda3\lib\site-packages (from matplotlib<4.0,>=3.1->torch-points3d) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\sjalu\anaconda3\lib\site-packages (from matplotlib<4.0,>=3.1->torch-points3d) (1.3.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\sjalu\anaconda3\lib\site-packages (from matplotlib<4.0,>=3.1->torch-points3d) (2.8.1)
Requirement already satisfied: cycler>=0.10 in c:\users\sjalu\anaconda3\lib\site-packages (from matplotlib<4.0,>=3.1->torch-points3d) (0.10.0)
Requirement already satisfied: setuptools in c:\users\sjalu\anaconda3\lib\site-packages (from numba<0.51.0,>=0.50.0->torch-points3d) (60.10.0)
Collecting llvmlite<0.34,>=0.33.0.dev0
  Using cached llvmlite-0.33.0-cp38-cp38-win_amd64.whl (15.0 MB)
Requirement already satisfied: torchvision in c:\users\sjalu\anaconda3\lib\site-packages (from pytorch_metric_learning<0.10.0,>=0.9.87.dev0->torch-points3d) (0.12.0)
Requirement already satisfied: scikit-learn in c:\users\sjalu\anaconda3\lib\site-packages (from pytorch_metric_learning<0.10.0,>=0.9.87.dev0->torch-points3d) (0.23.2)
Requirement already satisfied: scipy>=0.19.0 in c:\users\sjalu\anaconda3\lib\site-packages (from scikit-image<0.17.0,>=0.16.2->torch-points3d) (1.7.3)
Requirement already satisfied: networkx>=2.0 in c:\users\sjalu\anaconda3\lib\site-packages (from scikit-image<0.17.0,>=0.16.2->torch-points3d) (2.5)
Requirement already satisfied: imageio>=2.3.0 in c:\users\sjalu\anaconda3\lib\site-packages (from scikit-image<0.17.0,>=0.16.2->torch-points3d) (2.9.0)
Requirement already satisfied: PyWavelets>=0.4.0 in c:\users\sjalu\anaconda3\lib\site-packages (from scikit-image<0.17.0,>=0.16.2->torch-points3d) (1.1.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (2.3.3)
Requirement already satisfied: absl-py>=0.4 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (1.0.0)
Requirement already satisfied: protobuf>=3.6.0 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (3.19.1)
Requirement already satisfied: werkzeug>=0.11.15 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (1.0.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (1.8.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (0.4.6)
Requirement already satisfied: grpcio>=1.24.3 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (1.41.1)
Requirement already satisfied: markdown>=2.6.8 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (3.3.4)
Requirement already satisfied: wheel>=0.26 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (0.37.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\sjalu\anaconda3\lib\site-packages (from tensorboard<3.0,>=2.1->torch-points3d) (0.6.1)
Requirement already satisfied: typing_extensions in c:\users\sjalu\anaconda3\lib\site-packages (from torch<2.0.0,>=1.7.0->torch-points3d) (3.7.4.3)
Requirement already satisfied: pandas in c:\users\sjalu\anaconda3\lib\site-packages (from torch-geometric<2.0.0,>=1.3.2->torch-points3d) (1.2.4)
Requirement already satisfied: googledrivedownloader in c:\users\sjalu\anaconda3\lib\site-packages (from torch-geometric<2.0.0,>=1.3.2->torch-points3d) (0.4)
Requirement already satisfied: jinja2 in c:\users\sjalu\anaconda3\lib\site-packages (from torch-geometric<2.0.0,>=1.3.2->torch-points3d) (2.11.3)
Collecting python-louvain
  Using cached python_louvain-0.16-py3-none-any.whl
Requirement already satisfied: rdflib in c:\users\sjalu\anaconda3\lib\site-packages (from torch-geometric<2.0.0,>=1.3.2->torch-points3d) (6.1.1)
Requirement already satisfied: visdom in c:\users\sjalu\anaconda3\lib\site-packages (from torchnet<0.0.5,>=0.0.4->torch-points3d) (0.1.8.9)
Collecting configparser>=3.8.1
  Using cached configparser-5.2.0-py3-none-any.whl (19 kB)
Collecting subprocess32>=3.5.3
  Using cached subprocess32-3.5.4-py3-none-any.whl
Requirement already satisfied: docker-pycreds>=0.4.0 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (0.4.0)
Requirement already satisfied: PyYAML>=3.10 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (5.4.1)
Requirement already satisfied: sentry-sdk>=0.4.0 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (1.5.7)
Requirement already satisfied: Click>=7.0 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (7.1.2)
Requirement already satisfied: psutil>=5.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (5.8.0)
Collecting nvidia-ml-py3>=7.352.0
  Using cached nvidia_ml_py3-7.352.0-py3-none-any.whl
Requirement already satisfied: shortuuid>=0.5.0 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (1.0.8)
Requirement already satisfied: GitPython>=1.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (3.1.24)
Requirement already satisfied: watchdog>=0.8.3 in c:\users\sjalu\anaconda3\lib\site-packages (from wandb<0.9.0,>=0.8.18->torch-points3d) (1.0.2)
Collecting gql==0.2.0
  Using cached gql-0.2.0-py3-none-any.whl
Requirement already satisfied: promise<3,>=2.0 in c:\users\sjalu\anaconda3\lib\site-packages (from gql==0.2.0->wandb<0.9.0,>=0.8.18->torch-points3d) (2.3)
Collecting graphql-core<2,>=0.5.0
  Using cached graphql_core-1.1-py3-none-any.whl
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\sjalu\anaconda3\lib\site-packages (from GitPython>=1.0.0->wandb<0.9.0,>=0.8.18->torch-points3d) (4.0.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\sjalu\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<3.0,>=2.1->torch-points3d) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<3.0,>=2.1->torch-points3d) (4.2.4)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\sjalu\anaconda3\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<3.0,>=2.1->torch-points3d) (4.7.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\sjalu\anaconda3\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3.0,>=2.1->torch-points3d) (1.3.0)
Requirement already satisfied: decorator>=4.3.0 in c:\users\sjalu\anaconda3\lib\site-packages (from networkx>=2.0->scikit-image<0.17.0,>=0.16.2->torch-points3d) (5.0.6)
Requirement already satisfied: idna<3,>=2.5 in c:\users\sjalu\anaconda3\lib\site-packages (from requests[socks]>=2.12.0->gdown<4.0.0,>=3.12.0->torch-points3d) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\sjalu\anaconda3\lib\site-packages (from requests[socks]>=2.12.0->gdown<4.0.0,>=3.12.0->torch-points3d) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\sjalu\anaconda3\lib\site-packages (from requests[socks]>=2.12.0->gdown<4.0.0,>=3.12.0->torch-points3d) (2020.6.20)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\sjalu\anaconda3\lib\site-packages (from requests[socks]>=2.12.0->gdown<4.0.0,>=3.12.0->torch-points3d) (1.26.4)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\sjalu\anaconda3\lib\site-packages (from requests[socks]>=2.12.0->gdown<4.0.0,>=3.12.0->torch-points3d) (1.7.1)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\sjalu\anaconda3\lib\site-packages (from ipywidgets->open3d==0.10.0.0->torch-points3d) (5.0.5)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from ipywidgets->open3d==0.10.0.0->torch-points3d) (1.0.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\sjalu\anaconda3\lib\site-packages (from ipywidgets->open3d==0.10.0.0->torch-points3d) (5.1.3)
Requirement already satisfied: ipykernel>=4.5.1 in c:\users\sjalu\anaconda3\lib\site-packages (from ipywidgets->open3d==0.10.0.0->torch-points3d) (5.3.4)
Requirement already satisfied: ipython>=4.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from ipywidgets->open3d==0.10.0.0->torch-points3d) (7.22.0)
Requirement already satisfied: argon2-cffi in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (20.1.0)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (4.7.1)
Requirement already satisfied: terminado>=0.8.3 in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (0.9.4)
Requirement already satisfied: prometheus-client in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (0.10.1)
Requirement already satisfied: pyzmq>=17 in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (20.0.0)
Requirement already satisfied: Send2Trash>=1.5.0 in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (1.5.0)
Requirement already satisfied: tornado>=6.1 in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (6.1)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (6.1.12)
Requirement already satisfied: ipython-genutils in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (0.2.0)
Requirement already satisfied: nbconvert in c:\users\sjalu\anaconda3\lib\site-packages (from notebook->open3d==0.10.0.0->torch-points3d) (6.0.7)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\sjalu\anaconda3\lib\site-packages (from jinja2->torch-geometric<2.0.0,>=1.3.2->torch-points3d) (2.0.1)
Requirement already satisfied: pytz>=2017.3 in c:\users\sjalu\anaconda3\lib\site-packages (from pandas->torch-geometric<2.0.0,>=1.3.2->torch-points3d) (2021.1)
Requirement already satisfied: isodate in c:\users\sjalu\anaconda3\lib\site-packages (from rdflib->torch-geometric<2.0.0,>=1.3.2->torch-points3d) (0.6.1)
Requirement already satisfied: joblib>=0.11 in c:\users\sjalu\anaconda3\lib\site-packages (from scikit-learn->pytorch_metric_learning<0.10.0,>=0.9.87.dev0->torch-points3d) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from scikit-learn->pytorch_metric_learning<0.10.0,>=0.9.87.dev0->torch-points3d) (2.1.0)
Requirement already satisfied: websocket-client in c:\users\sjalu\anaconda3\lib\site-packages (from visdom->torchnet<0.0.5,>=0.0.4->torch-points3d) (1.2.1)
Requirement already satisfied: torchfile in c:\users\sjalu\anaconda3\lib\site-packages (from visdom->torchnet<0.0.5,>=0.0.4->torch-points3d) (0.1.0)
Requirement already satisfied: jsonpatch in c:\users\sjalu\anaconda3\lib\site-packages (from visdom->torchnet<0.0.5,>=0.0.4->torch-points3d) (1.32)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\sjalu\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->GitPython>=1.0.0->wandb<0.9.0,>=0.8.18->torch-points3d) (5.0.0)
Requirement already satisfied: jedi>=0.16 in c:\users\sjalu\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (0.17.2)
Requirement already satisfied: pickleshare in c:\users\sjalu\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (0.7.5)
Requirement already satisfied: backcall in c:\users\sjalu\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (0.2.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (3.0.17)
Requirement already satisfied: colorama in c:\users\sjalu\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (0.4.4)
Requirement already satisfied: pygments in c:\users\sjalu\anaconda3\lib\site-packages (from ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (2.8.1)
Requirement already satisfied: pywin32>=1.0 in c:\users\sjalu\anaconda3\lib\site-packages (from jupyter-core>=4.6.1->notebook->open3d==0.10.0.0->torch-points3d) (227)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\users\sjalu\anaconda3\lib\site-packages (from nbformat>=4.2.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (3.2.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\sjalu\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<3.0,>=2.1->torch-points3d) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<3.0,>=2.1->torch-points3d) (3.1.1)
Requirement already satisfied: pywinpty>=0.5 in c:\users\sjalu\anaconda3\lib\site-packages (from terminado>=0.8.3->notebook->open3d==0.10.0.0->torch-points3d) (0.5.7)
Requirement already satisfied: cffi>=1.0.0 in c:\users\sjalu\anaconda3\lib\site-packages (from argon2-cffi->notebook->open3d==0.10.0.0->torch-points3d) (1.14.5)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\sjalu\anaconda3\lib\site-packages (from jsonpatch->visdom->torchnet<0.0.5,>=0.0.4->torch-points3d) (2.2)
Requirement already satisfied: bleach in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (3.3.0)
Requirement already satisfied: jupyterlab-pygments in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (0.8.4)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (0.5.3)
Requirement already satisfied: entrypoints>=0.2.2 in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (0.3)
Requirement already satisfied: defusedxml in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (0.7.1)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (1.4.3)
Requirement already satisfied: testpath in c:\users\sjalu\anaconda3\lib\site-packages (from nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (0.4.4)
Requirement already satisfied: pycparser in c:\users\sjalu\anaconda3\lib\site-packages (from cffi>=1.0.0->argon2-cffi->notebook->open3d==0.10.0.0->torch-points3d) (2.20)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\users\sjalu\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (0.7.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\users\sjalu\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (0.17.3)
Requirement already satisfied: attrs>=17.4.0 in c:\users\sjalu\anaconda3\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (20.3.0)
Requirement already satisfied: async-generator in c:\users\sjalu\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (1.10)
Requirement already satisfied: nest-asyncio in c:\users\sjalu\anaconda3\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (1.5.1)
Requirement already satisfied: wcwidth in c:\users\sjalu\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0.0->ipywidgets->open3d==0.10.0.0->torch-points3d) (0.2.5)
Requirement already satisfied: webencodings in c:\users\sjalu\anaconda3\lib\site-packages (from bleach->nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (0.5.1)
Requirement already satisfied: packaging in c:\users\sjalu\anaconda3\lib\site-packages (from bleach->nbconvert->notebook->open3d==0.10.0.0->torch-points3d) (20.9)
Building wheels for collected packages: torch-points-kernels
  Building wheel for torch-points-kernels (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\chamfer_dist.py -> build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\cluster.py -> build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\cubic_feature_sampling.py -> build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\gridding.py -> build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\knn.py -> build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\metrics.py -> build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\torchpoints.py -> build\lib.win-amd64-3.8\torch_points_kernels
      copying torch_points_kernels\__init__.py -> build\lib.win-amd64-3.8\torch_points_kernels
      running build_ext
      c:\users\sjalu\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:322: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
        warnings.warn(f'Error checking compiler version for {compiler}: {error}')
      building 'torch_points_kernels.points_cpu' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      Error in atexit._run_exitfuncs:
      Traceback (most recent call last):
        File "c:\users\sjalu\anaconda3\lib\site-packages\colorama\ansitowin32.py", line 59, in closed
          return stream.closed
      ValueError: underlying buffer has been detached
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  **ERROR: Failed building wheel for torch-points-kernels**
  Running setup.py clean for torch-points-kernels
Failed to build torch-points-kernels
Installing collected packages: nvidia-ml-py3, subprocess32, plyfile, omegaconf, llvmlite, configparser, python-louvain, numba, hydra-core, graphql-core, torchnet, torch-points-kernels, torch-geometric, scikit-image, pytorch_metric_learning, gql, gdown, wandb, open3d, torch-points3d
  Attempting uninstall: omegaconf
    Found existing installation: omegaconf 2.1.1
    Uninstalling omegaconf-2.1.1:
      Successfully uninstalled omegaconf-2.1.1
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.36.0
ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Can anyone please help me where am I going wrong?

**Comment by CCInc** [comment]
Hi,

As it says in the error message, you'll need to install VC++ build tools:

 error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

I'm not sure how well windows is supported, though.

**Comment by Sandeepjalui93** [comment]
Thanks for the advice, the problem is solved.
