### ISSUE TITLE
Warning: "The down_conv_nn has a different size as radii. Make sure of have SharedRSConv"

### ISSUE THREAD

**Issue by ptoews** [torch-points3d/torch-points3d#735]
The warning in the title is shown when running the RSConv model, however the training still continues without further issues.
I tracked the source of this message down to this:

https://github.com/torch-points3d/torch-points3d/blob/663442df0ca843de3887ab15e74b8a1ac8a0fcd6/torch_points3d/modules/RSConv/dense.py#L276-L277

The two variables are directly coming from the config, which looks like this:

https://github.com/torch-points3d/torch-points3d/blob/663442df0ca843de3887ab15e74b8a1ac8a0fcd6/torch_points3d/applications/conf/rsconv/encoder_4.yaml#L7-L21

As you can see the first conv layer has different kind of arguments. According to the code there is a separate `xyz_raising` layer constructed using the second sublist. I assume that I can ignore this warning and the check above should be extended to handle the first layer in a different way. Is that correct?

**Comment by CCInc** [comment]
I'm not sure, to be honest. If the training works fine then it should be a non-issue. Feel free to submit a PR if you can
