### ISSUE TITLE
Use a model from PretrainedRegistry on custom dataset

### ISSUE THREAD

**Issue by jcorrochanoj** [torch-points3d/torch-points3d#739]
Hi, I am developing a segmentation task on my own dataset. Until now I was training a KPConv model from scratch, but I would like to use a pre-trained model.

I have been trying PretrainedRegistry but I am not able to adapt the downloaded model to my dataset. In particular, I have [downloaded ](https://github.com/torch-points3d/torch-points3d/blob/master/torch_points3d/applications/pretrained_api.py) the KPConv model for S3DIS in fold 6. First of all I would like to know if it is possible to use the model trained on this dataset in a different dataset.

I have been going through the documentation and the issues history looking for the necessary steps but I don't fount anything. Could someone tell me the necessary steps to download a pre-trained model and adapt it to my dataset?

Thank you very much and I hope this issue might be useful for more users.

**Comment by CCInc** [comment]
Have you seen the section for the pretrained API in the readme? It looks like once you have:

```python
from torch_points3d.applications.pretrained_api import PretainedRegistry

model = PretainedRegistry.from_pretrained("pointnet2_largemsg-s3dis-1")
```

The `model` variable should work as a normal Pytorch model, which you can run however you want. You can either use a dataset created for tp3d (and run the model using a script like forward_scripts) or simply iterate over your data:

```
model.eval()

for data in dataloader:
    model.forward(data)
    output = model.get_output()
```

Let me know if it helps!
