### ISSUE TITLE
SparseConv3d: RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by ptoews** [torch-points3d/torch-points3d#741]
I'm using the `SparseConv3d` model (`encoder_4.yaml` config) with the Minkowski backend (latest commit from master). During training, I get the following error:

```
File "[...]/venv/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1434, in backward
    loss.backward(*args, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "[...]/venv/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [3920, 256]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

I've tried the anomaly detection thing, however I can't find any changes in the output. Any ideas?

Thanks in advance.

**Comment by ptoews** [comment]
Here is a MWE:

```
import torch
import torch_geometric.data
import torch_points3d.applications.sparseconv3d
import torch_points3d.core.data_transform
import torch.nn.functional as F


t = torch_points3d.core.data_transform.GridSampling3D(0.02, quantize_coords=True)
train_dataset = [
    t(torch_geometric.data.Data(x=torch.randn((1000, 3)),
                                pos=torch.randn((1000, 3)),
                                y=torch.randn((256,))))
    for _ in range(100)
]
train_loader = torch_geometric.data.DataLoader(train_dataset)
model = torch_points3d.applications.sparseconv3d.SparseConv3d("encoder", 3, 4)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

for epoch in range(2):  # loop over the dataset multiple times
    for i, data in enumerate(train_loader, 0):
        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        out = model(data)
        y_hat = out.x.squeeze()
        loss = F.mse_loss(y_hat, data.y)
        loss.backward()
        optimizer.step()
```

**Comment by CCInc** [comment]
Are you using minkowski or torchsparse as your backend, btw?

**Comment by CCInc** [comment]
I don't get that error, I get a different one:

> Traceback (most recent call last):
>   File "/processing/torch-points3d/test3.py", line 25, in <module>
>     out = model(data)
>   File "/home/rock/miniconda3/envs/leo-tp3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/processing/torch-points3d/torch_points3d/applications/sparseconv3d.py", line 167, in forward
>     out = self.inner_modules[0](out)
>   File "/home/rock/miniconda3/envs/leo-tp3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/processing/torch-points3d/torch_points3d/core/base_conv/message_passing.py", line 144, in forward
>     x = self.pool(x, batch)
>   File "/home/rock/miniconda3/envs/leo-tp3d/lib/python3.9/site-packages/torch_geometric/nn/glob/glob.py", line 49, in global_mean_pool
>     return scatter(x, batch, dim=0, dim_size=size, reduce='mean')
>   File "/home/rock/miniconda3/envs/leo-tp3d/lib/python3.9/site-packages/torch_scatter/scatter.py", line 156, in scatter
>     return scatter_mean(src, index, dim, out, dim_size)
>   File "/home/rock/miniconda3/envs/leo-tp3d/lib/python3.9/site-packages/torch_scatter/scatter.py", line 41, in scatter_mean
>     out = scatter_sum(src, index, dim, out, dim_size)
>   File "/home/rock/miniconda3/envs/leo-tp3d/lib/python3.9/site-packages/torch_scatter/scatter.py", line 21, in scatter_sum
>     return out.scatter_add_(dim, index, src)
> RuntimeError: index -128 is out of bounds for dimension 0 with size 145

What version of everything are you using?

**Comment by ptoews** [comment]
My environment is pretty convoluted, so I reproduced the error with a fresh environment.
I'm using CUDA 11.3 and these are the commands that I ran in a fresh venv:
```
export CUDA_HOME=/usr/local/cuda-11.3/
pip install -U pip setuptools wheel
pip install torch==1.10.2+cu113 torchvision==0.11.3+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
pip install torch-scatter==2.0.9 torch-sparse==0.6.12 torch-cluster==1.5.9 torch-spline-conv==1.2.1 torch-geometric==1.7.2 -f https://data.pyg.org/whl/torch-1.10.2+cu113.html
pip install torch-points3d
pip install ninja
pip install -U git+https://github.com/NVIDIA/MinkowskiEngine --no-deps
```

At this point I get a different error when running the example:
```
lib/python3.8/site-packages/torch_points_kernels/points_cpu.so: undefined symbol: _ZNK2at6Tensor4normEN3c108optionalINS1_6ScalarEEENS1_8ArrayRefIlEEb
```

I compared versions with my original versions and realized that one was off, so I changed that:

```
pip install torch-points-kernels==0.7.0
```
At this point pip warned me that this version is in conflict with the requirements of torch-points3d, so this could already be the cause.
After installing `h5py` I ran the example again and reproduced the error.

I'm sorry for the complicated environment. The main reason is that torch-points3d doesn't support the newest hydra and numpy versions which I need, so in my original environment I built a custom version of torch-points3d with these specific dependency versions. But the custom build is not the issue as you can see.

**Comment by CCInc** [comment]
Sorry for the trouble - would you mind pulling from master and let me know what happens?

```
git clone git@github.com:torch-points3d/torch-points3d.git
pip uninstall torch-points3d
pip install -e ./torch-points3d
```

**Comment by ptoews** [comment]
Can't install it:

```
ERROR: Project file:///tmp/torch-points3d has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

**Comment by ptoews** [comment]
I tried installing it without the `-e` and it rolled back a lot of versions, e.g.
```
torch-1.8.1 
torch-points3d-0.2.0 
torch-sparse-0.6.12 
torchvision-0.9.1
```
Now, when running the example I get 
`OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory`

**Comment by CCInc** [comment]
It's very odd. I'm not sure why you're not running into the same error I am. I'm trying to find what causes the pooling error, then I'll try to replicate your issue.

**Comment by CCInc** [comment]
@ptoews sorry to take so long to look into this.

Thanks to this issue, I did find that the torchsparse backend isn't working properly with the encoder: https://github.com/torch-points3d/torch-points3d/pull/752

I wasn't able to recreate your issue in my environment (the only thing I did have to change in your test script was `y_hat = out.x.reshape(-1)`). 

Here are the versions I'm using:
```
pytorch                   1.9.1           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
pytorch-cluster           1.5.9           py39_torch_1.9.0_cu111    rusty1s
pytorch-geometric         1.7.2           py39_torch_1.9.0_cu111    rusty1s
pytorch-metric-learning   0.9.87.dev0              pypi_0    pypi
pytorch-scatter           2.0.9           py39_torch_1.9.0_cu111    rusty1s
pytorch-sparse            0.6.12          py39_torch_1.9.0_cu111    rusty1s
pytorch-spline-conv       1.2.1           py39_torch_1.9.0_cu111    rusty1s
torch-points-kernels      0.7.0                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
torchnet                  0.0.4                    pypi_0    pypi
torchsparse               1.4.0                    pypi_0    pypi
```

Are you using the latest verison of torchpoints3d (i.e. installed from the master branch, not the pip repo?)

**Comment by ptoews** [comment]
I found these two related discussion that might help:
- https://discuss.pytorch.org/t/inplace-errors-with-dropout-layers-with-pytorch-1-9-but-not-with-pytorch-1-10/137544
- https://github.com/NVlabs/FUNIT/issues/23

I was also able to get more information using the suggested anomaly detection with the MWE:

```
[...]/venv/lib/python3.7/site-packages/torch/autograd/__init__.py:156: UserWarning: Error detected in ReluBackward0. Traceback of forward call that caused the error:
  File "experiments/mwe_sparseconv3d_error.py", line 27, in <module>
    out = model(data)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/torch_points3d/applications/sparseconv3d.py", line 141, in forward
    data = self.down_modules[i](data)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/torch_points3d/modules/SparseConv3d/modules.py", line 161, in forward
    out = self.blocks(out)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/torch_points3d/modules/SparseConv3d/modules.py", line 45, in forward
    out = self.block(x)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/MinkowskiEngine/MinkowskiNonlinearity.py", line 42, in forward
    output = self.module(input.F)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "[...]/venv/lib/python3.7/site-packages/torch/nn/functional.py", line 1299, in relu
    result = torch.relu(input)
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
Traceback (most recent call last):
  File "experiments/mwe_sparseconv3d_error.py", line 30, in <module>
    loss.backward()
  File "[...]/venv/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "[...]/venv/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [746, 256]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

**Comment by CCInc** [comment]
Hmmm, interesting. Can you do a print on the model for me, in pytorch 1.10?

`print(model)`

It seems we need to set inplace to false for ReLU, which should already be done in minkowski. So I think we're missing one somewhere.

**Comment by ptoews** [comment]
Sure!

```
SparseConv3dEncoder(
  (down_modules): ModuleList(
    (0): ResNetDown(
      (conv_in): Seq(
        (0): Conv3d(in=3, out=32, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
        (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
      )
    )
    (1): ResNetDown(
      (conv_in): Seq(
        (0): Conv3d(in=32, out=32, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
        (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (blocks): Seq(
        (0): ResBlock(
          (block): Seq(
            (0): Conv3d(in=32, out=32, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=32, out=32, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
        )
      )
    )
    (2): ResNetDown(
      (conv_in): Seq(
        (0): Conv3d(in=32, out=32, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
        (1): BatchNorm1d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (blocks): Seq(
        (0): ResBlock(
          (block): Seq(
            (0): Conv3d(in=32, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
          (downsample): Seq(
            (0): Conv3d(in=32, out=64, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): ResBlock(
          (block): Seq(
            (0): Conv3d(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=64, out=64, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
        )
      )
    )
    (3): ResNetDown(
      (conv_in): Seq(
        (0): Conv3d(in=64, out=64, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
        (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (blocks): Seq(
        (0): ResBlock(
          (block): Seq(
            (0): Conv3d(in=64, out=128, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=128, out=128, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
          (downsample): Seq(
            (0): Conv3d(in=64, out=128, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): ResBlock(
          (block): Seq(
            (0): Conv3d(in=128, out=128, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=128, out=128, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
        )
      )
    )
    (4): ResNetDown(
      (conv_in): Seq(
        (0): Conv3d(in=128, out=128, kernel_size=[3, 3, 3], stride=[2, 2, 2], dilation=[1, 1, 1])
        (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (2): ReLU()
      )
      (blocks): Seq(
        (0): ResBlock(
          (block): Seq(
            (0): Conv3d(in=128, out=256, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=256, out=256, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
          (downsample): Seq(
            (0): Conv3d(in=128, out=256, kernel_size=[1, 1, 1], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
        )
        (1): ResBlock(
          (block): Seq(
            (0): Conv3d(in=256, out=256, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=256, out=256, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
        )
        (2): ResBlock(
          (block): Seq(
            (0): Conv3d(in=256, out=256, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (1): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Conv3d(in=256, out=256, kernel_size=[3, 3, 3], stride=[1, 1, 1], dilation=[1, 1, 1])
            (4): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (5): ReLU()
          )
        )
      )
    )
  )
  (inner_modules): ModuleList(
    (0): GlobalBaseModule(
      (nn): Sequential(
        (0): Sequential(
          (0): Linear(in_features=256, out_features=256, bias=True)
          (1): FastBatchNorm1d(
            (batch_norm): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (2): LeakyReLU(negative_slope=0.2)
        )
      )
    )
  )
  (up_modules): ModuleList()
)
```

**Comment by CCInc** [comment]
In your encoder config (sparseconv3d/encoder_4.yaml?) you could try adding the inplace parameter to LeakyReLU:

```
innermost:
    module_name: GlobalBaseModule
    activation:
        name: LeakyReLU
        negative_slope: 0.2
        inplace: False
    aggr: "mean"
    nn: [8*in_feat, 8*in_feat]
```

Not sure if that'll solve it though. It seems to be complaining about Minkowski's RELU, which we already pass inplace=false to.

**Comment by ptoews** [comment]
Well I tried but it didn't get through, the print showed the same model even if I changed the negative slope value.
I debugged it and verified that it uses the config I changed. Eventually I tracked it down to the constructor of `GlobalBaseModule`, where the changed values arrive, however in the `**kwargs`, which are ignored. See here:

https://github.com/torch-points3d/torch-points3d/blob/297f0e0906d99185216716144600d793f9fa16fb/torch_points3d/core/base_conv/message_passing.py#L131-L135

Which is called from here:

https://github.com/torch-points3d/torch-points3d/blob/297f0e0906d99185216716144600d793f9fa16fb/torch_points3d/models/base_architectures/unet.py#L382

where `args_innermost` is a dict only consisting of the `activation` entry here.

Anyway, I hardcoded the default value for `inplace` of the LeakyReLU in the `MLP` constructor to false which changed nothing.

**Comment by jaswanthbjk** [comment]
I ran into the same error while using pointgroup model.

**Comment by jaswanthbjk** [comment]
The reason for this issue happening is the Addition-Assignment(+=) operation present in the ResNet blocks.

For example [here](https://github.com/torch-points3d/torch-points3d/blob/297f0e0906d99185216716144600d793f9fa16fb/torch_points3d/modules/MinkowskiEngine/api_modules.py#L79)

`def forward(self, x):
        out = self.block(x)
        if self.downsample:
            out += self.downsample(x)
        else:
            out += x
        return `

I replaced this piece with 

`def forward(self, x):
        out_1 = self.block(x)
        if self.downsample:
            out = out_1 + self.downsample(x)
        else:
            out = out_1 + x
        return out`

It worked well

Since the tensors are (Minkowski) sparse-tensors I had to assign them to a new variable. But if they are generic (pytorch) tensors one could use tensor.clone().

I didn't test with Sparse3d backend.

**Comment by jaswanthbjk** [comment]
Did it solve the issue you are having ?

Yes I can raise a PR.

**Comment by ptoews** [comment]
I think there are more places where this has to be fixed, e.g. in order to fix my MWE above all I had to edit was this:
https://github.com/torch-points3d/torch-points3d/blob/297f0e0906d99185216716144600d793f9fa16fb/torch_points3d/modules/SparseConv3d/modules.py#L44-L50
and replace `out += ...` with `out = out + ...`. I will take a closer look at this once I fully understand the underlying issue.

**Comment by jaswanthbjk** [comment]
Yeah looks like it. I didn't use SparseConv3D, I used only Minkowski layers.

**Comment by jaswanthbjk** [comment]
**1) Why is this issue happening ?**
The operation out += 1 is an in-place operation (Modify the same memory pointed by out previously).

So when back-propagation is happening the memory gets modified twice. 

Since the memory versioning makes the tensor to have version_1 memory rather than version_0 memory (due to double modification). 

The backprop engine doesn't accept gradient with version_1 memory as the backprop is still at 0.

This leads to this issue.

**2) Why re-naming the variable is good ?** 
The out = out + 1 operation works good. 

But I think the compiler would be assigning a new unknown variable to the original memory.  

This does not help in debugging the code in future. So I decided to assign a new variable name.

**Comment by CCInc** [comment]
Hi @jaswanthbjk , thanks very much for looking into this and finding a resolution. @ptoews let me know if you will be able to perform this fix on SparseConv3d and can submit it as a PR, else I'll try to do it when I have some time. Thanks!

**Comment by ptoews** [comment]
@CCInc Unfortunately I don't have much time at the moment, maybe in a few weeks. I'd appreciate if you or someone else could do the PR.

**Comment by jaswanthbjk** [comment]
I think I made the necessary changes for SparseConv3D modules in the PR I raised.

**Comment by ptoews** [comment]
Thank you very much @jaswanthbjk @CCInc! Just confirmed that the latest git version works.
