### ISSUE TITLE
Inference method for PointGroup

### ISSUE THREAD

**Issue by jaswanthbjk** [torch-points3d/torch-points3d#765]
I trained PointGroup for Instance Segmenttion of point cloud using ScanNet dataset.

But How to use it for inference purposes on external point clouds ?

**Comment by CCInc** [comment]
Hi, you'll need to create a dataset for your data, or feed it through the model directly. You can take a look at [here](https://github.com/torch-points3d/torch-points3d/tree/master/forward_scripts) for an idea how to run inference on a trained model.

**Comment by eliasm56** [comment]
Hi Jaswanth,

Did you manage to work this out? I have the same issue.

Thanks,
Elias

**Comment by jaswanthbjk** [comment]
Hello @eliasm56 , Yes, I got it working. 

I will post it here in sometime

**Comment by jaswanthbjk** [comment]
The blue print of test data is as follows

```
  data = {}
  data["pos"] = sub_cloud[:, :3]
  data["rgb"] = sub_cloud[:, 3:]/255.0
  
  sampleid=idx
  
  data = Data(pos=data["pos"], rgb=data["rgb"])
  data["sampleid"] = torch.tensor([sampleid])
  # data = cT.SaveOriginalPosId()(data)
  data = transform_data(data)
  data = Batch.from_data_list([data])

```

The data object can be directly used as an input to the PointGroup model.

There is a small change to be done to set_input method in PointGroup model. It is as follows 

```
def set_input(self, data, device, task='train'):
        self.raw_pos = data.pos.to(device)
        self.input = data
        if task == 'train':
            all_labels = {l: data[l].to(device) for l in self.__REQUIRED_LABELS__}
            self.labels = PanopticLabels(**all_labels)
```

I'll do a pull request with changes to make forward_scripts work with pointgroup, Once I have free time available.
