### ISSUE TITLE
ImportError: cannot import name 'Config' from 'omegaconf'

### ISSUE THREAD

**Issue by neverland0621** [torch-points3d/torch-points3d#778]
hi，everyone。I am trying to reproduction this code with pointNet。 I followed the readme and install all the dependency，when i run this line：
poetry run python train.py task=segmentation models=segmentation/pointnet2 model_name=pointnet2_charlesssg data=segmentation/shapenet-fixed
 I encounter this error. does anyone know how to resolve this problem？ thank you in advance！
ImportError: cannot import name 'Config' from 'omegaconf'

**Comment by syoung114** [comment]
Check your omegaconf version and omegaconf dependencies. Errors like this could be from incompatible versions between python packages. I have omegaconf 2.0.6 and I don't have that error.

**Comment by neverland0621** [comment]
@syoung114  Thank you for replying，I check my omegaconf  version ，it is 2.0.6.  and I don’t know why this error still exist. 
do you have any other solution for this ，thanks！

**Comment by neverland0621** [comment]
I solved this problem by change the version of hydra-core from 0.11.2 to 1.0.7 ，thank you all.
